
import {IMathMenuItem} from "./Types";

export const mathMenuData: IMathMenuItem[] = [
  // Individual buttons
  {name: "subscript", icon: require("./images/sub.svg").default, key: "_" },
  {name: "superscript", icon: require("./images/super.svg").default, key: "^" },
  {name: "frac", icon: require("./images/frac.svg").default, tex: "\\frac"},
  {name: "sum", icon: require("./images/sum.svg").default, tex: "\\sum"},
  {name: "int", icon: require("./images/int.svg").default, tex: "\\int"},
  {name: "prod", icon: require("./images/prod.svg").default, tex: "\\prod"},

  {name: "sep", isSeparator: true},

  {name: "Insert matrix", icon: require("./images/matrix.svg").default, special: "show_matrix_modal" },
  {name: "Insert cases environment", icon: require("./images/cases.svg").default, tex: "\\cases"},

  {name: "Add row", icon: require("./images/tabular-feature_append-row.svg").default, key: "\n", ctrlKey: true, disabled: "not_inside_matrix"},
  {name: "Add column", icon: require("./images/tabular-feature_append-column.svg").default, key: "\n", ctrlKey: true, shiftKey: true, disabled: "not_inside_matrix"},
  {name: "Delete row", icon: require("./images/tabular-feature_delete-row.svg").default, chord: "M-m w d", disabled: "not_inside_matrix"},
  {name: "Delete column", icon: require("./images/tabular-feature_delete-column.svg").default, chord: "M-m c d", disabled: "not_inside_matrix"},

  {name: "sep", isSeparator: true},

  {name: "Insert ()", icon: require("./images/lparen_rparen.svg").default, rawTex: "\\left( \\hole \\right)"},
  {name: "Insert {}", icon: require("./images/lbracket_rbracket.svg").default, rawTex: "\\left[ \\hole \\right]"},
  {name: "Insert []", icon: require("./images/lbrace_rbrace.svg").default, rawTex: "\\left\\{ \\hole \\right\\}"},

  {name: "sep", isSeparator: true},

  {
    name: "Roots",
    icon: require("./images/root.svg").default,
    children: [
      {name: "Square root \\sqrt", icon: require("./images/sqrt.svg").default, tex: "\\sqrt"},
      {name: "Other root \\root", icon: require("./images/root.svg").default, tex: "\\Root"}
    ]
  },
  {
    name: "Spaces",
    icon: require("./images/space.svg").default,
    type: "text",
    children: [
      { name: "Thin space  ", tex: "\\,"},
      { name: "Medium space  ", tex: "\\:"},
      { name: "Thick space  ", tex: "\\;"},
      { name: "Quadratin space", tex: "\\quad"},
      { name: "Double quadratin space", tex: "\\qquad"},
      { name: "Negative space", tex: "\\!"},
      { name: "Phantom", tex: "\\phantom"},
      { name: "Horizontal phantom", tex: "\\hphantom"},
      { name: "Vertical phantom", tex: "\\vphantom"},
      { name: "Smash", tex: "\\smash"},
      { name: "Top smash", tex: "\\smasht"},
      { name: "Bottom smash", tex: "\\smashb"},
      { name: "Left overlap", tex: "\\mathllap"},
      { name: "Center overlap", tex: "\\mathclap"},
      { name: "Right overlap", tex: "\\mathrlap"}
    ]
  },
  {
    name: "Fractions",
    icon: require("./images/frac-square.svg").default,
    type: "text",
    children: [
      {name: "Standard", tex: "\\frac"},
      {name: "Nice fraction (3/4)", tex: "\\nicefrac"},
      {name: "Unit (km)", tex: "\\unitone"},
      {name: "Unit (864 m)", tex: "\\unittwo"},
      {name: "Unit frac", tex: "\\unitfrac"},
      {name: "Unit frac", tex: "\\unitfracthree"},
      {name: "Text frac", tex: "\\tfrac"},
      {name: "Display fraction", tex: "\\dfrac"},
      {name: "Continued frac", tex: "\\cfrac"},
      {name: "Continued frac", tex: "\\cfracleft"},
      {name: "Continued frac", tex: "\\cfracright"},
      {name: "Binomial", tex: "\\binom"},
      {name: "Text binomial", tex: "\\tbinom"},
      {name: "Display binomial", tex: "\\dbinom"}
    ]
  },
  {
    name: "Fonts",
    icon: require("./images/font.svg").default,
    children: [
      {name: "Roman", tex: "\\mathrm", icon: require("./images/mathrm.svg").default},
      {name: "Bold", tex: "\\mathbf", icon: require("./images/mathbf.svg").default},
      {name: "Bold symbol", tex: "\\boldsymbol", icon: require("./images/boldsymbol.svg").default},
      {name: "Sans serif", tex: "\\mathsf", icon: require("./images/mathsf.svg").default},
      {name: "Italic", tex: "\\mathit", icon: require("./images/mathit.svg").default},
      {name: "Typewriter", tex: "\\mathtt", icon: require("./images/mathtt.svg").default},
      {name: "Blackboard", tex: "\\mathbb", icon: require("./images/mathbb.svg").default},
      {name: "Fraktur", tex: "\\mathfrak", icon: require("./images/mathfrak.svg").default},
      {name: "Calligraphic", tex: "\\mathcal", icon: require("./images/mathcal.svg").default},
      {name: "Formal Script", tex: "\\mathscr", icon: require("./images/mathscr.svg").default},
      {name: "Normal text mode", tex: "\\textrm", icon: require("./images/textrm.svg").default}
    ]
  },
  {
    name: "Functions",
    icon: require("./images/functions.svg").default,
    type: "text",
    children: [
      {name: "arccos", tex: "\\arccos"},
      {name: "arcsin", tex: "\\arcsin"},
      {name: "arctan", tex: "\\arctan"},
      {name: "arg", tex: "\\arg"},
      {name: "bmod", tex: "\\bmod"},
      {name: "cos", tex: "\\cos"},
      {name: "cosh", tex: "\\cosh"},
      {name: "cot", tex: "\\cot"},
      {name: "coth", tex: "\\coth"},
      {name: "csc", tex: "\\csc"},
      {name: "deg", tex: "\\deg"},
      {name: "det", tex: "\\det"},
      {name: "dim", tex: "\\dim"},
      {name: "exp", tex: "\\exp"},
      {name: "gcd", tex: "\\gcd"},
      {name: "hom", tex: "\\hom"},
      {name: "inf", tex: "\\inf"},
      {name: "ker", tex: "\\ker"},
      {name: "lg", tex: "\\lg"},
      {name: "lim", tex: "\\lim"},
      {name: "liminf", tex: "\\liminf"},
      {name: "limsup", tex: "\\limsup"},
      {name: "ln", tex: "\\ln"},
      {name: "log", tex: "\\log"},
      {name: "max", tex: "\\max"},
      {name: "min", tex: "\\min"},
      {name: "sec", tex: "\\sec"},
      {name: "sin", tex: "\\sin"},
      {name: "sinh", tex: "\\sinh"},
      {name: "sup", tex: "\\sup"},
      {name: "tan", tex: "\\tan"},
      {name: "tanh", tex: "\\tanh"},
      {name: "Pr", tex: "\\Pr"}
    ]
  },
  {
    name: "Frame Decorations",
    icon: require("./images/hat.svg").default,
    children: [
      {name: "hat", tex: "\\hat", icon: require("./images/hat.svg").default},
      {name: "tilde", tex: "\\tilde", icon: require("./images/tilde.svg").default},
      {name: "bar", tex: "\\bar", icon: require("./images/bar.svg").default},
      {name: "grave", tex: "\\grave", icon: require("./images/grave.svg").default},
      {name: "dot", tex: "\\dot", icon: require("./images/dot.svg").default},
      {name: "check", tex: "\\check", icon: require("./images/check.svg").default},
      {name: "widehat", tex: "\\widehat", icon: require("./images/widehat.svg").default},
      {name: "widetilde", tex: "\\widetilde", icon: require("./images/widetilde.svg").default},
      {name: "utilde", tex: "\\utilde", icon: require("./images/utilde.svg").default},
      {name: "vec", tex: "\\vec", icon: require("./images/vec.svg").default},
      {name: "acute", tex: "\\acute", icon: require("./images/acute.svg").default},
      {name: "ddot", tex: "\\ddot", icon: require("./images/ddot.svg").default},
      {name: "dddot", tex: "\\dddot", icon: require("./images/dddot.svg").default},
      {name: "ddddot", tex: "\\ddddot", icon: require("./images/ddddot.svg").default},
      {name: "breve", tex: "\\breve", icon: require("./images/breve.svg").default},
      {name: "mathring", tex: "\\mathring", icon: require("./images/mathring.svg").default},
      {name: "overline", tex: "\\overline", icon: require("./images/overline.svg").default},
      {name: "overbrace", tex: "\\overbrace", icon: require("./images/overbrace.svg").default},
      {name: "overleftarrow", tex: "\\overleftarrow", icon: require("./images/overleftarrow.svg").default},
      {name: "overrightarrow", tex: "\\overrightarrow", icon: require("./images/overrightarrow.svg").default},
      {name: "overleftrightarrow", tex: "\\overleftrightarrow", icon: require("./images/overleftrightarrow.svg").default},
      {name: "underline", tex: "\\underline", icon: require("./images/underline.svg").default},
      {name: "underbrace", tex: "\\underbrace", icon: require("./images/underbrace.svg").default},
      {name: "underleftarrow", tex: "\\underleftarrow", icon: require("./images/underleftarrow.svg").default},
      {name: "underrightarrow", tex: "\\underrightarrow", icon: require("./images/underrightarrow.svg").default},
      {name: "underleftrightarrow", tex: "\\underleftrightarrow", icon: require("./images/underleftrightarrow.svg").default},
      {name: "cancel", tex: "\\cancel", icon: require("./images/cancel.svg").default},
      {name: "bcancel", tex: "\\bcancel", icon: require("./images/bcancel.svg").default},
      {name: "xcancel", tex: "\\xcancel", icon: require("./images/xcancel.svg").default},
      {name: "cancelto", tex: "\\cancelto", icon: require("./images/cancelto.svg").default},
      {name: "Insert left/right side scripts", tex: "\\sideset", icon: require("./images/sideset.svg").default},
      {name: "Insert right side scripts", tex: "\\sidesetr", icon: require("./images/sidesetr.svg").default},
      {name: "Insert left side scripts", tex: "\\sidesetl", icon: require("./images/sidesetl.svg").default},
      {name: "Insert side scripts", tex: "\\sidesetn", icon: require("./images/sidesetn.svg").default},
      {name: "overset", tex: "\\overset", icon: require("./images/overset.svg").default},
      {name: "underset", tex: "\\underset", icon: require("./images/underset.svg").default},
      {name: "stackrel", tex: "\\stackrel", icon: require("./images/stackrel.svg").default},
      {name: "stackrelthree", tex: "\\stackrelthree", icon: require("./images/stackrelthree.svg").default}
    ]
  },
  {
    name: "Big Operators",
    icon: require("./images/intop.svg").default,
    children: [
      {name: "intop", tex: "\\intop", icon: require("./images/intop.svg").default},
      {name: "int", tex: "\\int", icon: require("./images/int.svg").default},
      {name: "iint", tex: "\\iint", icon: require("./images/iint.svg").default},
      // {name: "iintop", tex: "\\iintop", icon: require("./images/iintop.svg").default},
      {name: "iiint", tex: "\\iiint", icon: require("./images/iiint.svg").default},
      // {name: "iiintop", tex: "\\iiintop", icon: require("./images/iiintop.svg").default},
      {name: "iiiint", tex: "\\iiiint", icon: require("./images/iiiint.svg").default},
      // {name: "iiiintop", tex: "\\iiiintop", icon: require("./images/iiiintop.svg").default},
      // {name: "dotsint", tex: "\\dotsint", icon: require("./images/dotsint.svg").default},
      // {name: "dotsintop", tex: "\\dotsintop", icon: require("./images/dotsintop.svg").default},
      // {name: "idotsint", tex: "\\idotsint", icon: require("./images/idotsint.svg").default},
      {name: "oint", tex: "\\oint", icon: require("./images/oint.svg").default},
      // {name: "ointop", tex: "\\ointop", icon: require("./images/ointop.svg").default},
      // {name: "oiint", tex: "\\oiint", icon: require("./images/oiint.svg").default},
      // {name: "oiintop", tex: "\\oiintop", icon: require("./images/oiintop.svg").default},
      // {name: "ointctrclockwiseop", tex: "\\ointctrclockwiseop", icon: require("./images/ointctrclockwiseop.svg").default},
      // {name: "ointctrclockwise", tex: "\\ointctrclockwise", icon: require("./images/ointctrclockwise.svg").default},
      // {name: "ointclockwiseop", tex: "\\ointclockwiseop", icon: require("./images/ointclockwiseop.svg").default},
      // {name: "ointclockwise", tex: "\\ointclockwise", icon: require("./images/ointclockwise.svg").default},
      // {name: "sqint", tex: "\\sqint", icon: require("./images/sqint.svg").default},
      // {name: "sqintop", tex: "\\sqintop", icon: require("./images/sqintop.svg").default},
      // {name: "sqiint", tex: "\\sqiint", icon: require("./images/sqiint.svg").default},
      // {name: "sqiintop", tex: "\\sqiintop", icon: require("./images/sqiintop.svg").default},
      // {name: "fint", tex: "\\fint", icon: require("./images/fint.svg").default},
      // {name: "fintop", tex: "\\fintop", icon: require("./images/fintop.svg").default},
      // {name: "landupint", tex: "\\landupint", icon: require("./images/landupint.svg").default},
      // {name: "landupintop", tex: "\\landupintop", icon: require("./images/landupintop.svg").default},
      // {name: "landdownint", tex: "\\landdownint", icon: require("./images/landdownint.svg").default},
      // {name: "landdownintop", tex: "\\landdownintop", icon: require("./images/landdownintop.svg").default},
      // {name: "varint", tex: "\\varint", icon: require("./images/varint.svg").default},
      // {name: "varoint", tex: "\\varoint", icon: require("./images/varoint.svg").default},
      // {name: "varoiint", tex: "\\varoiint", icon: require("./images/varoiint.svg").default},
      // {name: "varoiintop", tex: "\\varoiintop", icon: require("./images/varoiintop.svg").default},
      // {name: "varointclockwise", tex: "\\varointclockwise", icon: require("./images/varointclockwise.svg").default},
      // {name: "varointclockwiseop", tex: "\\varointclockwiseop", icon: require("./images/varointclockwiseop.svg").default},
      // {name: "varointctrclockwise", tex: "\\varointctrclockwise", icon: require("./images/varointctrclockwise.svg").default},
      // {name: "varointctrclockwiseop", tex: "\\varointctrclockwiseop", icon: require("./images/varointctrclockwiseop.svg").default},
      {name: "sum", tex: "\\sum", icon: require("./images/sum.svg").default},
      {name: "prod", tex: "\\prod", icon: require("./images/prod.svg").default},
      {name: "coprod", tex: "\\coprod", icon: require("./images/coprod.svg").default},
      {name: "bigsqcup", tex: "\\bigsqcup", icon: require("./images/bigsqcup.svg").default},
      {name: "bigotimes", tex: "\\bigotimes", icon: require("./images/bigotimes.svg").default},
      {name: "bigodot", tex: "\\bigodot", icon: require("./images/bigodot.svg").default},
      {name: "bigoplus", tex: "\\bigoplus", icon: require("./images/bigoplus.svg").default},
      {name: "bigcap", tex: "\\bigcap", icon: require("./images/bigcap.svg").default},
      {name: "bigcup", tex: "\\bigcup", icon: require("./images/bigcup.svg").default},
      {name: "biguplus", tex: "\\biguplus", icon: require("./images/biguplus.svg").default},
      {name: "bigvee", tex: "\\bigvee", icon: require("./images/bigvee.svg").default},
      {name: "bigwedge", tex: "\\bigwedge", icon: require("./images/bigwedge.svg").default}
    ]
  },
  {
    name: "Miscellaneous",
    icon: require("./images/nabla.svg").default,
    children: [
      {icon: require("./images/nabla.svg").default, tex: "\\nabla"},
      {icon: require("./images/partial.svg").default, tex: "\\partial"},
      {icon: require("./images/infty.svg").default, tex: "\\infty"},
      {icon: require("./images/prime.svg").default, tex: "\\prime"},
      {icon: require("./images/ell.svg").default, tex: "\\ell"},
      {icon: require("./images/emptyset.svg").default, tex: "\\emptyset"},
      {icon: require("./images/exists.svg").default, tex: "\\exists"},
      {icon: require("./images/forall.svg").default, tex: "\\forall"},
      {icon: require("./images/imath.svg").default, tex: "\\imath"},
      {icon: require("./images/jmath.svg").default, tex: "\\jmath"},
      {icon: require("./images/Re.svg").default, tex: "\\Re"},
      {icon: require("./images/Im.svg").default, tex: "\\Im"},
      {icon: require("./images/aleph.svg").default, tex: "\\aleph"},
      {icon: require("./images/wp.svg").default, tex: "\\wp"},
      {icon: require("./images/hbar.svg").default, tex: "\\hbar"},
      {icon: require("./images/angle.svg").default, tex: "\\angle"},
      {icon: require("./images/top.svg").default, tex: "\\top"},
      {icon: require("./images/bot.svg").default, tex: "\\bot"},
      {icon: require("./images/vert2.svg").default, tex: "\\Vert"},
      {icon: require("./images/neg.svg").default, tex: "\\neg"},
      {icon: require("./images/flat.svg").default, tex: "\\flat"},
      {icon: require("./images/natural.svg").default, tex: "\\natural"},
      {icon: require("./images/sharp.svg").default, tex: "\\sharp"},
      {icon: require("./images/surd.svg").default, tex: "\\surd"},
      // {icon: require("./images/lhook.svg").default, tex: "\\lhook"},
      // {icon: require("./images/rhook.svg").default, tex: "\\rhook"},
      {icon: require("./images/triangle.svg").default, tex: "\\triangle"},
      {icon: require("./images/diamondsuit.svg").default, tex: "\\diamondsuit"},
      {icon: require("./images/heartsuit.svg").default, tex: "\\heartsuit"},
      {icon: require("./images/clubsuit.svg").default, tex: "\\clubsuit"},
      {icon: require("./images/spadesuit.svg").default, tex: "\\spadesuit"},
      // {icon: "textrm \\AA", tex: "\\textrm \AA"},
      // {icon: "textrm \\O", tex: "\\textrm \O"},
      // {icon: "mathcircumflex", tex: "\\mathcircumflex"},
      // {icon: "_", tex: "\\_"},
      // {icon: "textdegree", tex: "\\textdegree"},
      // {icon: "mathdollar", tex: "\\mathdollar"},
      // {icon: "mathparagraph", tex: "\\mathparagraph"},
      // {icon: "mathsection", tex: "\\mathsection"},
      // {icon: "mathrm T", tex: "\\mathrm T"},
      // {icon: "mathbb N", tex: "\\mathbb N"},
      // {icon: "mathbb Z", tex: "\\mathbb Z"},
      // {icon: "mathbb Q", tex: "\\mathbb Q"},
      // {icon: "mathbb R", tex: "\\mathbb R"},
      // {icon: "mathbb C", tex: "\\mathbb C"},
      // {icon: "mathbb H", tex: "\\mathbb H"},
      // {icon: "mathcal F", tex: "\\mathcal F"},
      // {icon: "mathcal L", tex: "\\mathcal L"},
      // {icon: "mathcal H", tex: "\\mathcal H"},
      // {icon: "mathcal O", tex: "\\mathcal O"}
    ]
  },
  {
    name: "Greek",
    icon: require("./images/alpha.svg").default,
    children: [
      { name: "alpha", tex: "\\alpha", icon: require("./images/alpha.svg").default },
      { name: "beta", tex: "\\beta", icon: require("./images/beta.svg").default },
      { name: "gamma", tex: "\\gamma", icon: require("./images/gamma.svg").default },
      { name: "delta", tex: "\\delta", icon: require("./images/delta.svg").default },
      { name: "epsilon", tex: "\\epsilon", icon: require("./images/epsilon.svg").default },
      { name: "varepsilon", tex: "\\varepsilon", icon: require("./images/varepsilon.svg").default },
      { name: "zeta", tex: "\\zeta", icon: require("./images/zeta.svg").default },
      { name: "eta", tex: "\\eta", icon: require("./images/eta.svg").default },
      { name: "theta", tex: "\\theta", icon: require("./images/theta.svg").default },
      { name: "vartheta", tex: "\\vartheta", icon: require("./images/vartheta.svg").default },
      { name: "iota", tex: "\\iota", icon: require("./images/iota.svg").default },
      { name: "kappa", tex: "\\kappa", icon: require("./images/kappa.svg").default },
      { name: "lambda", tex: "\\lambda", icon: require("./images/lambda.svg").default },
      { name: "mu", tex: "\\mu", icon: require("./images/mu.svg").default },
      { name: "nu", tex: "\\nu", icon: require("./images/nu.svg").default },
      { name: "xi", tex: "\\xi", icon: require("./images/xi.svg").default },
      { name: "pi", tex: "\\pi", icon: require("./images/pi.svg").default },
      { name: "varpi", tex: "\\varpi", icon: require("./images/varpi.svg").default },
      { name: "rho", tex: "\\rho", icon: require("./images/rho.svg").default },
      { name: "varrho", tex: "\\varrho", icon: require("./images/varrho.svg").default },
      { name: "sigma", tex: "\\sigma", icon: require("./images/sigma.svg").default },
      { name: "varsigma", tex: "\\varsigma", icon: require("./images/varsigma.svg").default },
      { name: "tau", tex: "\\tau", icon: require("./images/tau.svg").default },
      { name: "upsilon", tex: "\\upsilon", icon: require("./images/upsilon.svg").default },
      { name: "phi", tex: "\\phi", icon: require("./images/phi.svg").default },
      { name: "varphi", tex: "\\varphi", icon: require("./images/varphi.svg").default },
      { name: "chi", tex: "\\chi", icon: require("./images/chi.svg").default },
      { name: "psi", tex: "\\psi", icon: require("./images/psi.svg").default },
      { name: "omega", tex: "\\omega", icon: require("./images/omega.svg").default },
      { name: "Gamma", tex: "\\Gamma", icon: require("./images/gamma2.svg").default },
      { name: "Delta", tex: "\\Delta", icon: require("./images/delta2.svg").default },
      { name: "Theta", tex: "\\Theta", icon: require("./images/theta2.svg").default },
      { name: "Lambda", tex: "\\Lambda", icon: require("./images/lambda2.svg").default },
      { name: "Xi", tex: "\\Xi", icon: require("./images/xi2.svg").default },
      { name: "Pi", tex: "\\Pi", icon: require("./images/pi2.svg").default },
      { name: "Sigma", tex: "\\Sigma", icon: require("./images/sigma2.svg").default },
      { name: "Upsilon", tex: "\\Upsilon", icon: require("./images/upsilon2.svg").default },
      { name: "Phi", tex: "\\Phi", icon: require("./images/phi2.svg").default },
      { name: "Psi", tex: "\\Psi", icon: require("./images/psi2.svg").default },
      { name: "Omega", tex: "\\Omega", icon: require("./images/omega2.svg").default },
      { name: "varGamma", tex: "\\varGamma", icon: require("./images/vargamma2.svg").default },
      { name: "varDelta", tex: "\\varDelta", icon: require("./images/vardelta2.svg").default },
      { name: "varTheta", tex: "\\varTheta", icon: require("./images/vartheta2.svg").default },
      { name: "varLambda", tex: "\\varLambda", icon: require("./images/varlambda2.svg").default },
      { name: "varXi", tex: "\\varXi", icon: require("./images/varxi2.svg").default },
      { name: "varPi", tex: "\\varPi", icon: require("./images/varpi2.svg").default },
      { name: "varSigma", tex: "\\varSigma", icon: require("./images/varsigma2.svg").default },
      { name: "varUpsilon", tex: "\\varUpsilon", icon: require("./images/varupsilon2.svg").default },
      { name: "varPhi", tex: "\\varPhi", icon: require("./images/varphi2.svg").default },
      { name: "varPsi", tex: "\\varPsi", icon: require("./images/varpsi2.svg").default },
      { name: "varOmega", tex: "\\varOmega", icon: require("./images/varomega2.svg").default }
    ]
  },
  {
    name: "Arrows",
    icon: require("./images/leftarrow.svg").default,
    children: [
      {icon: require("./images/leftarrow.svg").default, tex: "\\leftarrow"},
      {icon: require("./images/rightarrow.svg").default, tex: "\\rightarrow"},
      {icon: require("./images/downarrow.svg").default, tex: "\\downarrow"},
      {icon: require("./images/uparrow.svg").default, tex: "\\uparrow"},
      {icon: require("./images/updownarrow.svg").default, tex: "\\updownarrow"},
      {icon: require("./images/leftrightarrow.svg").default, tex: "\\leftrightarrow"},
      {icon: require("./images/leftarrow2.svg").default, tex: "\\Leftarrow"},
      {icon: require("./images/rightarrow2.svg").default, tex: "\\Rightarrow"},
      {icon: require("./images/downarrow2.svg").default, tex: "\\Downarrow"},
      {icon: require("./images/uparrow2.svg").default, tex: "\\Uparrow"},
      {icon: require("./images/updownarrow2.svg").default, tex: "\\Updownarrow"},
      {icon: require("./images/leftrightarrow2.svg").default, tex: "\\Leftrightarrow"},
      {icon: require("./images/longleftrightarrow2.svg").default, tex: "\\Longleftrightarrow"},
      {icon: require("./images/longleftarrow2.svg").default, tex: "\\Longleftarrow"},
      {icon: require("./images/longrightarrow2.svg").default, tex: "\\Longrightarrow"},
      {icon: require("./images/longleftrightarrow.svg").default, tex: "\\longleftrightarrow"},
      {icon: require("./images/longleftarrow.svg").default, tex: "\\longleftarrow"},
      {icon: require("./images/longrightarrow.svg").default, tex: "\\longrightarrow"},
      {icon: require("./images/leftharpoondown.svg").default, tex: "\\leftharpoondown"},
      {icon: require("./images/rightharpoondown.svg").default, tex: "\\rightharpoondown"},
      {icon: require("./images/mapsto.svg").default, tex: "\\mapsto"},
      {icon: require("./images/longmapsto.svg").default, tex: "\\longmapsto"},
      {icon: require("./images/nwarrow.svg").default, tex: "\\nwarrow"},
      {icon: require("./images/nearrow.svg").default, tex: "\\nearrow"},
      {icon: require("./images/leftharpoonup.svg").default, tex: "\\leftharpoonup"},
      {icon: require("./images/rightharpoonup.svg").default, tex: "\\rightharpoonup"},
      {icon: require("./images/hookleftarrow.svg").default, tex: "\\hookleftarrow"},
      {icon: require("./images/hookrightarrow.svg").default, tex: "\\hookrightarrow"},
      {icon: require("./images/swarrow.svg").default, tex: "\\swarrow"},
      {icon: require("./images/searrow.svg").default, tex: "\\searrow"},
      {icon: require("./images/rightleftharpoons.svg").default, tex: "\\rightleftharpoons"}
    ]
  },
  {
    name: "Arrows (extended)",
    icon: require("./images/dashleftarrow.svg").default,
    children: [
      {icon: require("./images/dashleftarrow.svg").default, tex: "\\dashleftarrow"},
      {icon: require("./images/dashrightarrow.svg").default, tex: "\\dashrightarrow"},
      {icon: require("./images/leftleftarrows.svg").default, tex: "\\leftleftarrows"},
      {icon: require("./images/leftrightarrows.svg").default, tex: "\\leftrightarrows"},
      {icon: require("./images/rightrightarrows.svg").default, tex: "\\rightrightarrows"},
      {icon: require("./images/rightleftarrows.svg").default, tex: "\\rightleftarrows"},
      {icon: require("./images/Lleftarrow.svg").default, tex: "\\Lleftarrow"},
      {icon: require("./images/Rrightarrow.svg").default, tex: "\\Rrightarrow"},
      {icon: require("./images/twoheadleftarrow.svg").default, tex: "\\twoheadleftarrow"},
      {icon: require("./images/twoheadrightarrow.svg").default, tex: "\\twoheadrightarrow"},
      {icon: require("./images/leftarrowtail.svg").default, tex: "\\leftarrowtail"},
      {icon: require("./images/rightarrowtail.svg").default, tex: "\\rightarrowtail"},
      {icon: require("./images/looparrowleft.svg").default, tex: "\\looparrowleft"},
      {icon: require("./images/looparrowright.svg").default, tex: "\\looparrowright"},
      {icon: require("./images/curvearrowleft.svg").default, tex: "\\curvearrowleft"},
      {icon: require("./images/curvearrowright.svg").default, tex: "\\curvearrowright"},
      {icon: require("./images/circlearrowleft.svg").default, tex: "\\circlearrowleft"},
      {icon: require("./images/circlearrowright.svg").default, tex: "\\circlearrowright"},
      {icon: require("./images/Lsh.svg").default, tex: "\\Lsh"},
      {icon: require("./images/Rsh.svg").default, tex: "\\Rsh"},
      {icon: require("./images/upuparrows.svg").default, tex: "\\upuparrows"},
      {icon: require("./images/downdownarrows.svg").default, tex: "\\downdownarrows"},
      {icon: require("./images/upharpoonleft.svg").default, tex: "\\upharpoonleft"},
      {icon: require("./images/upharpoonright.svg").default, tex: "\\upharpoonright"},
      {icon: require("./images/downharpoonleft.svg").default, tex: "\\downharpoonleft"},
      {icon: require("./images/downharpoonright.svg").default, tex: "\\downharpoonright"},
      {icon: require("./images/leftrightharpoons.svg").default, tex: "\\leftrightharpoons"},
      {icon: require("./images/rightleftharpoons.svg").default, tex: "\\rightleftharpoons"},
      {icon: require("./images/rightsquigarrow.svg").default, tex: "\\rightsquigarrow"},
      {icon: require("./images/leftrightsquigarrow.svg").default, tex: "\\leftrightsquigarrow"},
      {icon: require("./images/nleftarrow.svg").default, tex: "\\nleftarrow"},
      {icon: require("./images/nrightarrow.svg").default, tex: "\\nrightarrow"},
      {icon: require("./images/nleftrightarrow.svg").default, tex: "\\nleftrightarrow"},
      {icon: require("./images/nleftarrow2.svg").default, tex: "\\nLeftarrow"},
      {icon: require("./images/nrightarrow2.svg").default, tex: "\\nRightarrow"},
      {icon: require("./images/nleftrightarrow2.svg").default, tex: "\\nLeftrightarrow"},
      {icon: require("./images/multimap.svg").default, tex: "\\multimap"},
      // {icon: require("./images/shortleftarrow.svg").default, tex: "\\shortleftarrow"},
      // {icon: require("./images/shortrightarrow.svg").default, tex: "\\shortrightarrow"},
      // {icon: require("./images/shortuparrow.svg").default, tex: "\\shortuparrow"},
      // {icon: require("./images/shortdownarrow.svg").default, tex: "\\shortdownarrow"},
      // {icon: require("./images/leftrightarroweq.svg").default, tex: "\\leftrightarroweq"},
      // {icon: require("./images/curlyveedownarrow.svg").default, tex: "\\curlyveedownarrow"},
      // {icon: require("./images/curlyveeuparrow.svg").default, tex: "\\curlyveeuparrow"},
      // {icon: require("./images/nnwarrow.svg").default, tex: "\\nnwarrow"},
      // {icon: require("./images/nnearrow.svg").default, tex: "\\nnearrow"},
      // {icon: require("./images/sswarrow.svg").default, tex: "\\sswarrow"},
      // {icon: require("./images/ssearrow.svg").default, tex: "\\ssearrow"},
      // {icon: require("./images/curlywedgeuparrow.svg").default, tex: "\\curlywedgeuparrow"},
      // {icon: require("./images/curlywedgedownarrow.svg").default, tex: "\\curlywedgedownarrow"},
      // {icon: require("./images/leftrightarrowtriangle.svg").default, tex: "\\leftrightarrowtriangle"},
      // {icon: require("./images/leftarrowtriangle.svg").default, tex: "\\leftarrowtriangle"},
      // {icon: require("./images/rightarrowtriangle.svg").default, tex: "\\rightarrowtriangle"},
      // {icon: require("./images/mapsto2.svg").default, tex: "\\Mapsto"},
      // {icon: require("./images/mapsfrom.svg").default, tex: "\\mapsfrom"},
      // {icon: require("./images/mapsfrom2.svg").default, tex: "\\Mapsfrom"},
      // {icon: require("./images/longmapsto2.svg").default, tex: "\\Longmapsto"},
      // {icon: require("./images/longmapsfrom.svg").default, tex: "\\longmapsfrom"},
      // {icon: require("./images/longmapsfrom2.svg").default, tex: "\\Longmapsfrom"},
      {icon: require("./images/xleftarrow.svg").default, tex: "\\xleftarrow"},
      {icon: require("./images/xrightarrow.svg").default, tex: "\\xrightarrow"}
    ]
  },
  {
    name: "Operators",
    icon: require("./images/pm.svg").default,
    children: [
      {name: "pm", tex: "\\pm", icon: require("./images/pm.svg").default},
      {name: "cap", tex: "\\cap", icon: require("./images/cap.svg").default},
      {name: "diamond", tex: "\\diamond", icon: require("./images/diamond.svg").default},
      {name: "oplus", tex: "\\oplus", icon: require("./images/oplus.svg").default},
      {name: "mp", tex: "\\mp", icon: require("./images/mp.svg").default},
      {name: "cup", tex: "\\cup", icon: require("./images/cup.svg").default},
      {name: "bigtriangleup", tex: "\\bigtriangleup", icon: require("./images/bigtriangleup.svg").default},
      {name: "ominus", tex: "\\ominus", icon: require("./images/ominus.svg").default},
      {name: "times", tex: "\\times", icon: require("./images/times.svg").default},
      {name: "uplus", tex: "\\uplus", icon: require("./images/uplus.svg").default},
      {name: "bigtriangledown", tex: "\\bigtriangledown", icon: require("./images/bigtriangledown.svg").default},
      {name: "otimes", tex: "\\otimes", icon: require("./images/otimes.svg").default},
      {name: "div", tex: "\\div", icon: require("./images/div.svg").default},
      {name: "sqcap", tex: "\\sqcap", icon: require("./images/sqcap.svg").default},
      {name: "triangleright", tex: "\\triangleright", icon: require("./images/triangleright.svg").default},
      {name: "oslash", tex: "\\oslash", icon: require("./images/oslash.svg").default},
      {name: "cdot", tex: "\\cdot", icon: require("./images/cdot.svg").default},
      {name: "sqcup", tex: "\\sqcup", icon: require("./images/sqcup.svg").default},
      {name: "triangleleft", tex: "\\triangleleft", icon: require("./images/triangleleft.svg").default},
      {name: "odot", tex: "\\odot", icon: require("./images/odot.svg").default},
      {name: "star", tex: "\\star", icon: require("./images/star.svg").default},
      {name: "ast", tex: "\\ast", icon: require("./images/ast.svg").default},
      {name: "vee", tex: "\\vee", icon: require("./images/vee.svg").default},
      {name: "amalg", tex: "\\amalg", icon: require("./images/amalg.svg").default},
      {name: "bigcirc", tex: "\\bigcirc", icon: require("./images/bigcirc.svg").default},
      {name: "setminus", tex: "\\setminus", icon: require("./images/setminus.svg").default},
      {name: "wedge", tex: "\\wedge", icon: require("./images/wedge.svg").default},
      {name: "dagger", tex: "\\dagger", icon: require("./images/dagger.svg").default},
      {name: "circ", tex: "\\circ", icon: require("./images/circ.svg").default},
      {name: "bullet", tex: "\\bullet", icon: require("./images/bullet.svg").default},
      {name: "wr", tex: "\\wr", icon: require("./images/wr.svg").default},
      {name: "ddagger", tex: "\\ddagger", icon: require("./images/ddagger.svg").default},
      {name: "smallint", tex: "\\smallint", icon: require("./images/smallint.svg").default}
    ]
  },
  {
    name: "Operators (extended)",
    icon: require("./images/dotplus.svg").default,
    children: [
      {icon: require("./images/dotplus.svg").default, tex: "\\dotplus"},
      {icon: require("./images/smallsetminus.svg").default, tex: "\\smallsetminus"},
      {icon: require("./images/cap2.svg").default, tex: "\\Cap"},
      {icon: require("./images/cup2.svg").default, tex: "\\Cup"},
      {icon: require("./images/barwedge.svg").default, tex: "\\barwedge"},
      {icon: require("./images/veebar.svg").default, tex: "\\veebar"},
      {icon: require("./images/doublebarwedge.svg").default, tex: "\\doublebarwedge"},
      {icon: require("./images/boxminus.svg").default, tex: "\\boxminus"},
      {icon: require("./images/boxtimes.svg").default, tex: "\\boxtimes"},
      {icon: require("./images/boxdot.svg").default, tex: "\\boxdot"},
      {icon: require("./images/boxplus.svg").default, tex: "\\boxplus"},
      // {icorequire("./images/n").default: boxastrequire, tex: "\\boxast"},
      // {icon: boxbarrequire, tex: "\\boxbar"},
      // {icon: boxslashrequire, tex: "\\boxslash"},
      // {icon: boxbslashrequire, tex: "\\boxbslash"},
      // {icon: boxcirclerequire, tex: "\\boxcircle"},
      // {icon: boxboxrequire, tex: "\\boxbox"},
      // {icon: boxemptyrequire, tex: "\\boxempty"},
      {icon: require("./images/divideontimes.svg").default, tex: "\\divideontimes"},
      {icon: require("./images/ltimes.svg").default, tex: "\\ltimes"},
      {icon: require("./images/rtimes.svg").default, tex: "\\rtimes"},
      {icon: require("./images/leftthreetimes.svg").default, tex: "\\leftthreetimes"},
      {icon: require("./images/rightthreetimes.svg").default, tex: "\\rightthreetimes"},
      {icon: require("./images/curlywedge.svg").default, tex: "\\curlywedge"},
      {icon: require("./images/curlyvee.svg").default, tex: "\\curlyvee"},
      {icon: require("./images/circleddash.svg").default, tex: "\\circleddash"},
      {icon: require("./images/circledast.svg").default, tex: "\\circledast"},
      {icon: require("./images/circledcirc.svg").default, tex: "\\circledcirc"},
      {icon: require("./images/centerdot.svg").default, tex: "\\centerdot"},
      {icon: require("./images/intercal.svg").default, tex: "\\intercal"},
      {icon: require("./images/implies.svg").default, tex: "\\implies"},
      {icon: require("./images/impliedby.svg").default, tex: "\\impliedby"},
      // {icon: bigcurlyveerequire, tex: "\\bigcurlyvee"},
      // {icon: bigcurlywedgerequire, tex: "\\bigcurlywedge"},
      // {icon: bigsqcaprequire, tex: "\\bigsqcap"},
      // {icon: bigboxrequire, tex: "\\bigbox"},
      // {icon: bigparallelrequire, tex: "\\bigparallel"},
      // {icon: biginterleaverequire, tex: "\\biginterleave"},
      // {icon: bignplusrequire, tex: "\\bignplus"},
      // {icon: nplusrequire, tex: "\\nplus"},
      // {icon: Yuprequire, tex: "\\Yup"},
      // {icon: Ydownrequire, tex: "\\Ydown"},
      // {icon: Yleftrequire, tex: "\\Yleft"},
      // {icon: Yrightrequire, tex: "\\Yright"},
      // {icon: obarrequire, tex: "\\obar"},
      // {icon: obslashrequire, tex: "\\obslash"},
      // {icon: ocirclerequire, tex: "\\ocircle"},
      // {icon: olessthanrequire, tex: "\\olessthan"},
      // {icon: ogreaterthanrequire, tex: "\\ogreaterthan"},
      // {icon: oveerequire, tex: "\\ovee"},
      // {icon: owedgerequire, tex: "\\owedge"},
      // {icon: varcurlyveerequire, tex: "\\varcurlyvee"},
      // {icon: varcurlywedgerequire, tex: "\\varcurlywedge"},
      // {icon: vartimesrequire, tex: "\\vartimes"},
      // {icon: varotimesrequire, tex: "\\varotimes"},
      // {icon: varoastrequire, tex: "\\varoast"},
      // {icon: varobarrequire, tex: "\\varobar"},
      // {icon: varodotrequire, tex: "\\varodot"},
      // {icon: varoslashrequire, tex: "\\varoslash"},
      // {icon: varobslashrequire, tex: "\\varobslash"},
      // {icon: varocirclerequire, tex: "\\varocircle"},
      // {icon: varoplusrequire, tex: "\\varoplus"},
      // {icon: varominusrequire, tex: "\\varominus"},
      // {icon: varoveerequire, tex: "\\varovee"},
      // {icon: varowedgerequire, tex: "\\varowedge"},
      // {icon: varolessthanrequire, tex: "\\varolessthan"},
      // {icon: varogreaterthanrequire, tex: "\\varogreaterthan"},
      // {icon: varbigcircrequire, tex: "\\varbigcirc"}
    ]
  },
  {
    name: "Relations",
    icon: require("./images/leq.svg").default,
    children: [
      {icon: require("./images/leq.svg").default,  tex: "\\leq"},
      {icon: require("./images/geq.svg").default,  tex: "\\geq"},
      {icon: require("./images/equiv.svg").default,  tex: "\\equiv"},
      {icon: require("./images/models.svg").default,  tex: "\\models"},
      {icon: require("./images/prec.svg").default,  tex: "\\prec"},
      {icon: require("./images/succ.svg").default,  tex: "\\succ"},
      {icon: require("./images/sim.svg").default,  tex: "\\sim"},
      {icon: require("./images/perp.svg").default,  tex: "\\perp"},
      {icon: require("./images/preceq.svg").default,  tex: "\\preceq"},
      {icon: require("./images/succeq.svg").default,  tex: "\\succeq"},
      {icon: require("./images/simeq.svg").default,  tex: "\\simeq"},
      {icon: require("./images/mid.svg").default,  tex: "\\mid"},
      {icon: require("./images/ll.svg").default,  tex: "\\ll"},
      {icon: require("./images/gg.svg").default,  tex: "\\gg"},
      {icon: require("./images/asymp.svg").default,  tex: "\\asymp"},
      {icon: require("./images/parallel.svg").default,  tex: "\\parallel"},
      {icon: require("./images/subset.svg").default,  tex: "\\subset"},
      {icon: require("./images/supset.svg").default,  tex: "\\supset"},
      {icon: require("./images/approx.svg").default,  tex: "\\approx"},
      {icon: require("./images/smile.svg").default,  tex: "\\smile"},
      {icon: require("./images/subseteq.svg").default,  tex: "\\subseteq"},
      {icon: require("./images/supseteq.svg").default,  tex: "\\supseteq"},
      {icon: require("./images/cong.svg").default,  tex: "\\cong"},
      {icon: require("./images/frown.svg").default,  tex: "\\frown"},
      {icon: require("./images/sqsubseteq.svg").default,  tex: "\\sqsubseteq"},
      {icon: require("./images/sqsupseteq.svg").default,  tex: "\\sqsupseteq"},
      {icon: require("./images/doteq.svg").default,  tex: "\\doteq"},
      {icon: require("./images/neq.svg").default,  tex: "\\neq"},
      {icon: require("./images/in.svg").default, tex: "\\in"},
      {icon: require("./images/ni.svg").default, tex: "\\ni"},
      {icon: require("./images/propto.svg").default, tex: "\\propto"},
      {icon: require("./images/notin.svg").default, tex: "\\notin"},
      {icon: require("./images/vdash.svg").default, tex: "\\vdash"},
      {icon: require("./images/dashv.svg").default, tex: "\\dashv"},
      {icon: require("./images/bowtie.svg").default, tex: "\\bowtie"},
      {icon: require("./images/iff.svg").default, tex: "\\iff"},
      {icon: require("./images/not.svg").default, tex: "\\not"},
      {icon: require("./images/land.svg").default, tex: "\\land"},
      {icon: require("./images/lor.svg").default, tex: "\\lor"},
      {icon: require("./images/lnot.svg").default, tex: "\\lnot"}
    ]
  },

  {
    name: "Relations (extended)",
    icon: require("./images/leqq.svg").default,
    children: [
      {icon: require("./images/leqq.svg").default, tex: "\\leqq"},
      {icon: require("./images/geqq.svg").default, tex: "\\geqq"},
      {icon: require("./images/leqslant.svg").default, tex: "\\leqslant"},
      {icon: require("./images/geqslant.svg").default, tex: "\\geqslant"},
      {icon: require("./images/eqslantless.svg").default, tex: "\\eqslantless"},
      {icon: require("./images/eqslantgtr.svg").default, tex: "\\eqslantgtr"},
      {icon: require("./images/eqsim.svg").default, tex: "\\eqsim"},
      {icon: require("./images/lesssim.svg").default, tex: "\\lesssim"},
      {icon: require("./images/gtrsim.svg").default, tex: "\\gtrsim"},
      {icon: require("./images/apprge.svg").default, tex: "\\apprge"},
      {icon: require("./images/apprle.svg").default, tex: "\\apprle"},
      {icon: require("./images/lessapprox.svg").default, tex: "\\lessapprox"},
      {icon: require("./images/gtrapprox.svg").default, tex: "\\gtrapprox"},
      {icon: require("./images/approxeq.svg").default, tex: "\\approxeq"},
      {icon: require("./images/triangleq.svg").default, tex: "\\triangleq"},
      {icon: require("./images/lessdot.svg").default, tex: "\\lessdot"},
      {icon: require("./images/gtrdot.svg").default, tex: "\\gtrdot"},
      {icon: require("./images/lll.svg").default, tex: "\\lll"},
      {icon: require("./images/ggg.svg").default, tex: "\\ggg"},
      {icon: require("./images/lessgtr.svg").default, tex: "\\lessgtr"},
      {icon: require("./images/gtrless.svg").default, tex: "\\gtrless"},
      {icon: require("./images/lesseqgtr.svg").default, tex: "\\lesseqgtr"},
      {icon: require("./images/gtreqless.svg").default, tex: "\\gtreqless"},
      {icon: require("./images/lesseqqgtr.svg").default, tex: "\\lesseqqgtr"},
      {icon: require("./images/gtreqqless.svg").default, tex: "\\gtreqqless"},
      {icon: require("./images/eqcirc.svg").default, tex: "\\eqcirc"},
      {icon: require("./images/circeq.svg").default, tex: "\\circeq"},
      {icon: require("./images/thicksim.svg").default, tex: "\\thicksim"},
      {icon: require("./images/thickapprox.svg").default, tex: "\\thickapprox"},
      {icon: require("./images/backsim.svg").default, tex: "\\backsim"},
      {icon: require("./images/backsimeq.svg").default, tex: "\\backsimeq"},
      {icon: require("./images/subseteqq.svg").default, tex: "\\subseteqq"},
      {icon: require("./images/supseteqq.svg").default, tex: "\\supseteqq"},
      {icon: require("./images/subset2.svg").default, tex: "\\Subset"},
      {icon: require("./images/supset2.svg").default, tex: "\\Supset"},
      {icon: require("./images/sqsubset.svg").default, tex: "\\sqsubset"},
      {icon: require("./images/sqsupset.svg").default, tex: "\\sqsupset"},
      {icon: require("./images/preccurlyeq.svg").default, tex: "\\preccurlyeq"},
      {icon: require("./images/succcurlyeq.svg").default, tex: "\\succcurlyeq"},
      {icon: require("./images/curlyeqprec.svg").default, tex: "\\curlyeqprec"},
      {icon: require("./images/curlyeqsucc.svg").default, tex: "\\curlyeqsucc"},
      {icon: require("./images/precsim.svg").default, tex: "\\precsim"},
      {icon: require("./images/succsim.svg").default, tex: "\\succsim"},
      {icon: require("./images/precapprox.svg").default, tex: "\\precapprox"},
      {icon: require("./images/succapprox.svg").default, tex: "\\succapprox"},
      {icon: require("./images/vartriangleleft.svg").default, tex: "\\vartriangleleft"},
      {icon: require("./images/vartriangleright.svg").default, tex: "\\vartriangleright"},
      {icon: require("./images/trianglelefteq.svg").default, tex: "\\trianglelefteq"},
      {icon: require("./images/trianglerighteq.svg").default, tex: "\\trianglerighteq"},
      {icon: require("./images/bumpeq.svg").default, tex: "\\bumpeq"},
      {icon: require("./images/bumpeq2.svg").default, tex: "\\Bumpeq"},
      {icon: require("./images/doteqdot.svg").default, tex: "\\doteqdot"},
      {icon: require("./images/risingdotseq.svg").default, tex: "\\risingdotseq"},
      {icon: require("./images/fallingdotseq.svg").default, tex: "\\fallingdotseq"},
      {icon: require("./images/vdash2.svg").default, tex: "\\vDash"},
      {icon: require("./images/Vvdash.svg").default, tex: "\\Vvdash"},
      {icon: require("./images/vdash3.svg").default, tex: "\\Vdash"},
      {icon: require("./images/shortmid.svg").default, tex: "\\shortmid"},
      {icon: require("./images/shortparallel.svg").default, tex: "\\shortparallel"},
      {icon: require("./images/smallsmile.svg").default, tex: "\\smallsmile"},
      {icon: require("./images/smallfrown.svg").default, tex: "\\smallfrown"},
      {icon: require("./images/blacktriangleleft.svg").default, tex: "\\blacktriangleleft"},
      {icon: require("./images/blacktriangleright.svg").default, tex: "\\blacktriangleright"},
      {icon: require("./images/because.svg").default, tex: "\\because"},
      {icon: require("./images/therefore.svg").default, tex: "\\therefore"},
      {icon: require("./images/wasytherefore.svg").default, tex: "\\wasytherefore"},
      {icon: require("./images/backepsilon.svg").default, tex: "\\backepsilon"},
      {icon: require("./images/varpropto.svg").default, tex: "\\varpropto"},
      {icon: require("./images/between.svg").default, tex: "\\between"},
      {icon: require("./images/pitchfork.svg").default, tex: "\\pitchfork"},
      {icon: require("./images/trianglelefteqslant.svg").default, tex: "\\trianglelefteqslant"},
      {icon: require("./images/trianglerighteqslant.svg").default, tex: "\\trianglerighteqslant"},
      {icon: require("./images/inplus.svg").default, tex: "\\inplus"},
      {icon: require("./images/niplus.svg").default, tex: "\\niplus"},
      {icon: require("./images/subsetplus.svg").default, tex: "\\subsetplus"},
      {icon: require("./images/supsetplus.svg").default, tex: "\\supsetplus"},
      {icon: require("./images/subsetpluseq.svg").default, tex: "\\subsetpluseq"},
      {icon: require("./images/supsetpluseq.svg").default, tex: "\\supsetpluseq"},
      {icon: require("./images/minuso.svg").default, tex: "\\minuso"},
      {icon: require("./images/baro.svg").default, tex: "\\baro"},
      {icon: require("./images/sslash.svg").default, tex: "\\sslash"},
      {icon: require("./images/bbslash.svg").default, tex: "\\bbslash"},
      {icon: require("./images/moo.svg").default, tex: "\\moo"},
      {icon: require("./images/merge.svg").default, tex: "\\merge"},
      {icon: require("./images/invneg.svg").default, tex: "\\invneg"},
      {icon: require("./images/lbag.svg").default, tex: "\\lbag"},
      {icon: require("./images/rbag.svg").default, tex: "\\rbag"},
      {icon: require("./images/interleave.svg").default, tex: "\\interleave"},
      {icon: require("./images/leftslice.svg").default, tex: "\\leftslice"},
      {icon: require("./images/rightslice.svg").default, tex: "\\rightslice"},
      {icon: require("./images/oblong.svg").default, tex: "\\oblong"},
      {icon: require("./images/talloblong.svg").default, tex: "\\talloblong"},
      {icon: require("./images/fatsemi.svg").default, tex: "\\fatsemi"},
      {icon: require("./images/fatslash.svg").default, tex: "\\fatslash"},
      {icon: require("./images/fatbslash.svg").default, tex: "\\fatbslash"},
      {icon: require("./images/ldotp.svg").default, tex: "\\ldotp"},
      {icon: require("./images/cdotp.svg").default, tex: "\\cdotp"},
      {icon: require("./images/colon.svg").default, tex: "\\colon"},
      {icon: require("./images/dblcolon.svg").default, tex: "\\dblcolon"},
      {icon: require("./images/vcentcolon.svg").default, tex: "\\vcentcolon"},
      {icon: require("./images/colonapprox.svg").default, tex: "\\colonapprox"},
      {icon: require("./images/colonapprox2.svg").default, tex: "\\Colonapprox"},
      {icon: require("./images/coloneq.svg").default, tex: "\\coloneq"},
      {icon: require("./images/coloneq2.svg").default, tex: "\\Coloneq"},
      {icon: require("./images/coloneqq.svg").default, tex: "\\coloneqq"},
      {icon: require("./images/coloneqq2.svg").default, tex: "\\Coloneqq"},
      {icon: require("./images/colonsim.svg").default, tex: "\\colonsim"},
      {icon: require("./images/colonsim2.svg").default, tex: "\\Colonsim"},
      {icon: require("./images/eqcolon.svg").default, tex: "\\eqcolon"},
      {icon: require("./images/eqcolon2.svg").default, tex: "\\Eqcolon"},
      {icon: require("./images/eqqcolon.svg").default, tex: "\\eqqcolon"},
      {icon: require("./images/eqqcolon2.svg").default, tex: "\\Eqqcolon"},
      {icon: require("./images/wasypropto.svg").default, tex: "\\wasypropto"},
      {icon: require("./images/logof.svg").default, tex: "\\logof"},
      {icon: require("./images/join2.svg").default, tex: "\\Join"}
    ]
  },
  {
    name: "Negative Relations (extended)",
    icon: require("./images/nless.svg").default,
    children: [
      {icon: require("./images/nless.svg").default, tex: "\\nless"},
      {icon: require("./images/ngtr.svg").default, tex: "\\ngtr"},
      {icon: require("./images/nleq.svg").default, tex: "\\nleq"},
      {icon: require("./images/ngeq.svg").default, tex: "\\ngeq"},
      {icon: require("./images/nleqslant.svg").default, tex: "\\nleqslant"},
      {icon: require("./images/ngeqslant.svg").default, tex: "\\ngeqslant"},
      {icon: require("./images/nleqq.svg").default, tex: "\\nleqq"},
      {icon: require("./images/ngeqq.svg").default, tex: "\\ngeqq"},
      {icon: require("./images/lneq.svg").default, tex: "\\lneq"},
      {icon: require("./images/gneq.svg").default, tex: "\\gneq"},
      {icon: require("./images/lneqq.svg").default, tex: "\\lneqq"},
      {icon: require("./images/gneqq.svg").default, tex: "\\gneqq"},
      {icon: require("./images/lvertneqq.svg").default, tex: "\\lvertneqq"},
      {icon: require("./images/gvertneqq.svg").default, tex: "\\gvertneqq"},
      {icon: require("./images/lnsim.svg").default, tex: "\\lnsim"},
      {icon: require("./images/gnsim.svg").default, tex: "\\gnsim"},
      {icon: require("./images/lnapprox.svg").default, tex: "\\lnapprox"},
      {icon: require("./images/gnapprox.svg").default, tex: "\\gnapprox"},
      {icon: require("./images/nprec.svg").default, tex: "\\nprec"},
      {icon: require("./images/nsucc.svg").default, tex: "\\nsucc"},
      {icon: require("./images/npreceq.svg").default, tex: "\\npreceq"},
      {icon: require("./images/nsucceq.svg").default, tex: "\\nsucceq"},
      {icon: require("./images/precneqq.svg").default, tex: "\\precneqq"},
      {icon: require("./images/succneqq.svg").default, tex: "\\succneqq"},
      {icon: require("./images/precnsim.svg").default, tex: "\\precnsim"},
      {icon: require("./images/succnsim.svg").default, tex: "\\succnsim"},
      {icon: require("./images/precnapprox.svg").default, tex: "\\precnapprox"},
      {icon: require("./images/succnapprox.svg").default, tex: "\\succnapprox"},
      {icon: require("./images/subsetneq.svg").default, tex: "\\subsetneq"},
      {icon: require("./images/supsetneq.svg").default, tex: "\\supsetneq"},
      {icon: require("./images/subsetneqq.svg").default, tex: "\\subsetneqq"},
      {icon: require("./images/supsetneqq.svg").default, tex: "\\supsetneqq"},
      {icon: require("./images/nsubseteq.svg").default, tex: "\\nsubseteq"},
      {icon: require("./images/nsubseteqq.svg").default, tex: "\\nsubseteqq"},
      {icon: require("./images/nsupseteq.svg").default, tex: "\\nsupseteq"},
      {icon: require("./images/nsupseteqq.svg").default, tex: "\\nsupseteqq"},
      {icon: require("./images/nvdash.svg").default, tex: "\\nvdash"},
      {icon: require("./images/nvdash2.svg").default, tex: "\\nvDash"},
      {icon: require("./images/nvdash3.svg").default, tex: "\\nVDash"},
      {icon: require("./images/nvdash4.svg").default, tex: "\\nVdash"},
      {icon: require("./images/varsubsetneq.svg").default, tex: "\\varsubsetneq"},
      {icon: require("./images/varsupsetneq.svg").default, tex: "\\varsupsetneq"},
      {icon: require("./images/varsubsetneqq.svg").default, tex: "\\varsubsetneqq"},
      {icon: require("./images/varsupsetneqq.svg").default, tex: "\\varsupsetneqq"},
      {icon: require("./images/ntriangleleft.svg").default, tex: "\\ntriangleleft"},
      {icon: require("./images/ntriangleright.svg").default, tex: "\\ntriangleright"},
      {icon: require("./images/ntrianglelefteq.svg").default, tex: "\\ntrianglelefteq"},
      {icon: require("./images/ntrianglerighteq.svg").default, tex: "\\ntrianglerighteq"},
      {icon: require("./images/ncong.svg").default, tex: "\\ncong"},
      {icon: require("./images/nsim.svg").default, tex: "\\nsim"},
      {icon: require("./images/nmid.svg").default, tex: "\\nmid"},
      {icon: require("./images/nshortmid.svg").default, tex: "\\nshortmid"},
      {icon: require("./images/nparallel.svg").default, tex: "\\nparallel"},
      {icon: require("./images/nshortparallel.svg").default, tex: "\\nshortparallel"},
      {icon: require("./images/ntrianglelefteqslant.svg").default, tex: "\\ntrianglelefteqslant"},
      {icon: require("./images/ntrianglerighteqslant.svg").default, tex: "\\ntrianglerighteqslant"}
    ]
  },
  {
    name: "Dots",
    icon: require("./images/dots.svg").default,
    children: [
      {name: require("./images/ldots.svg").default, tex: "\\ldots", icon: require("./images/ldots.svg").default},
      {name: require("./images/cdots.svg").default, tex: "\\cdots", icon: require("./images/cdots.svg").default},
      {name: require("./images/vdots.svg").default, tex: "\\vdots", icon: require("./images/vdots.svg").default},
      {name: require("./images/ddots.svg").default, tex: "\\ddots", icon: require("./images/ddots.svg").default},
      {name: require("./images/iddots.svg").default, tex: "\\iddots", icon: require("./images/iddots.svg").default}
    ]
  },
  {
    name: "Delimiters (fixed size)",
    icon: require("./images/brokenvert.svg").default,
    children: [
      {icon: require("./images/brokenvert.svg").default, tex: "\\brokenvert"},
      {icon: require("./images/lfloor.svg").default, tex: "\\lfloor"},
      {icon: require("./images/rfloor.svg").default, tex: "\\rfloor"},
      {icon: require("./images/lceil.svg").default, tex: "\\lceil"},
      {icon: require("./images/rceil.svg").default, tex: "\\rceil"},
      {icon: require("./images/llbracket.svg").default, tex: "\\llbracket"},
      {icon: require("./images/rrbracket.svg").default, tex: "\\rrbracket"},
      {icon: require("./images/llfloor.svg").default, tex: "\\llfloor"},
      {icon: require("./images/rrfloor.svg").default, tex: "\\rrfloor"},
      {icon: require("./images/llceil.svg").default, tex: "\\llceil"},
      {icon: require("./images/rrceil.svg").default, tex: "\\rrceil"},
      {icon: require("./images/lbag2.svg").default, tex: "\\Lbag"},
      {icon: require("./images/rbag2.svg").default, tex: "\\Rbag"},
      {icon: require("./images/llparenthesis.svg").default, tex: "\\llparenthesis"},
      {icon: require("./images/rrparenthesis.svg").default, tex: "\\rrparenthesis"},
      {icon: require("./images/binampersand.svg").default, tex: "\\binampersand"},
      {icon: require("./images/bindnasrepma.svg").default, tex: "\\bindnasrepma"}
    ]
  },
  {
    name: "Miscellaneous (extended)",
    icon: require("./images/fint.svg").default, // TODO
    children: [
      {icon: require("./images/digamma.svg").default, tex: "\\digamma"},
      {icon: require("./images/varkappa.svg").default, tex: "\\varkappa"},
      {icon: require("./images/beth.svg").default, tex: "\\beth"},
      {icon: require("./images/daleth.svg").default, tex: "\\daleth"},
      {icon: require("./images/gimel.svg").default, tex: "\\gimel"},
      {icon: require("./images/ulcorner.svg").default, tex: "\\ulcorner"},
      {icon: require("./images/urcorner.svg").default, tex: "\\urcorner"},
      {icon: require("./images/llcorner.svg").default, tex: "\\llcorner"},
      {icon: require("./images/lrcorner.svg").default, tex: "\\lrcorner"},
      {icon: require("./images/hbar.svg").default, tex: "\\hbar"},
      {icon: require("./images/hslash.svg").default, tex: "\\hslash"},
      {icon: require("./images/vartriangle.svg").default, tex: "\\vartriangle"},
      {icon: require("./images/triangledown.svg").default, tex: "\\triangledown"},
      {icon: require("./images/square.svg").default, tex: "\\square"},
      // {icon: "square2", tex: "\\Square"},
      // {icon: "checkedbox2", tex: "\\CheckedBox"},
      {icon: require("./images/xbox3.svg").default, tex: "\\XBox"},
      {icon: require("./images/lozenge.svg").default, tex: "\\lozenge"},
      // {icon: "wasylozenge", tex: "\\wasylozenge"},
      {icon: require("./images/circledR.svg").default, tex: "\\circledR"},
      {icon: require("./images/circledS.svg").default, tex: "\\circledS"},
      {icon: require("./images/measuredangle.svg").default, tex: "\\measuredangle"},
      // {icon: "varangle", tex: "\\varangle"},
      {icon: require("./images/nexists.svg").default, tex: "\\nexists"},
      {icon: require("./images/mho.svg").default, tex: "\\mho"},
      {icon: require("./images/Finv.svg").default, tex: "\\Finv"},
      {icon: require("./images/Game.svg").default, tex: "\\Game"},
      {icon: require("./images/Bbbk.svg").default, tex: "\\Bbbk"},
      {icon: require("./images/backprime.svg").default, tex: "\\backprime"},
      {icon: require("./images/varnothing.svg").default, tex: "\\varnothing"},
      {icon: require("./images/blacktriangle.svg").default, tex: "\\blacktriangle"},
      {icon: require("./images/blacktriangledown.svg").default, tex: "\\blacktriangledown"},
      {icon: require("./images/blacksquare.svg").default, tex: "\\blacksquare"},
      {icon: require("./images/blacklozenge.svg").default, tex: "\\blacklozenge"},
      {icon: require("./images/bigstar.svg").default, tex: "\\bigstar"},
      {icon: require("./images/sphericalangle.svg").default, tex: "\\sphericalangle"},
      {icon: require("./images/complement.svg").default, tex: "\\complement"},
      {icon: require("./images/eth.svg").default, tex: "\\eth"},
      {icon: require("./images/diagup.svg").default, tex: "\\diagup"},
      {icon: require("./images/diagdown.svg").default, tex: "\\diagdown"},
      // {icon: "lightning", tex: "\\lightning"},
      // {icon: "varcopyright", tex: "\\varcopyright"},
      // {icon: "bowtie2", tex: "\\Bowtie"},
      // {icon: "diameter", tex: "\\diameter"},
      // {icon: "invdiameter", tex: "\\invdiameter"},
      // {icon: "bell", tex: "\\bell"},
      // {icon: "hexagon", tex: "\\hexagon"},
      // {icon: "varhexagon", tex: "\\varhexagon"},
      // {icon: "pentagon", tex: "\\pentagon"},
      // {icon: "octagon", tex: "\\octagon"},
      // {icon: "smiley", tex: "\\smiley"},
      // {icon: "blacksmiley", tex: "\\blacksmiley"},
      // {icon: "frownie", tex: "\\frownie"},
      // {icon: "sun", tex: "\\sun"},
      {icon: require("./images/leadsto.svg").default, tex: "\\leadsto"},
      // {icon: "circle2", tex: "\\Circle"},
      // {icon: "leftcircle2", tex: "\\Leftcircle"},
      // {icon: "rightcircle2", tex: "\\Rightcircle"},
      // {icon: "circle3", tex: "\\CIRCLE"},
      // {icon: "leftcircle3", tex: "\\LEFTCIRCLE"},
      // {icon: "rightcircle3", tex: "\\RIGHTCIRCLE"},
      // {icon: "leftcircle4", tex: "\\LEFTcircle"},
      // {icon: "rightcircle4", tex: "\\RIGHTcircle"},
      // {icon: "leftturn", tex: "\\leftturn"},
      // {icon: "rightturn", tex: "\\rightturn"},
      // {icon: "AC", tex: "\\AC"},
      // {icon: "HF", tex: "\\HF"},
      // {icon: "VHF", tex: "\\VHF"},
      // {icon: "photon", tex: "\\photon"},
      // {icon: "gluon", tex: "\\gluon"},
      // {icon: "permil", tex: "\\permil"},
      // {icon: "cent", tex: "\\cent"},
      {icon: require("./images/yen.svg").default, tex: "\\yen"},
      // {icon: "hexstar", tex: "\\hexstar"},
      // {icon: "varhexstar", tex: "\\varhexstar"},
      // {icon: "davidsstar", tex: "\\davidsstar"},
      {icon: require("./images/maltese.svg").default, tex: "\\maltese"},
      // {icon: "kreuz", tex: "\\kreuz"},
      // {icon: "ataribox", tex: "\\ataribox"},
      // {icon: "xbox3", tex: "\\XBox"},
      // {icon: "checked", tex: "\\checked"},
      {icon: require("./images/checkmark.svg").default, tex: "\\checkmark"},
      // {icon: "eighthnote", tex: "\\eighthnote"},
      // {icon: "quarternote", tex: "\\quarternote"},
      // {icon: "halfnote", tex: "\\halfnote"},
      // {icon: "fullnote", tex: "\\fullnote"},
      // {icon: "twonotes", tex: "\\twonotes"},
      // {icon: "female", tex: "\\female"},
      // {icon: "male", tex: "\\male"},
      // {icon: "vernal", tex: "\\vernal"},
      // {icon: "ascnode", tex: "\\ascnode"},
      // {icon: "descnode", tex: "\\descnode"},
      // {icon: "fullmoon", tex: "\\fullmoon"},
      // {icon: "newmoon", tex: "\\newmoon"},
      // {icon: "leftmoon", tex: "\\leftmoon"},
      // {icon: "rightmoon", tex: "\\rightmoon"},
      // {icon: "astrosun", tex: "\\astrosun"},
      // {icon: "mercury", tex: "\\mercury"},
      // {icon: "venus", tex: "\\venus"},
      // {icon: "earth", tex: "\\earth"},
      // {icon: "mars", tex: "\\mars"},
      // {icon: "jupiter", tex: "\\jupiter"},
      // {icon: "saturn", tex: "\\saturn"},
      // {icon: "uranus", tex: "\\uranus"},
      // {icon: "neptune", tex: "\\neptune"},
      // {icon: "pluto", tex: "\\pluto"},
      // {icon: "aries", tex: "\\aries"},
      // {icon: "taurus", tex: "\\taurus"},
      // {icon: "gemini", tex: "\\gemini"},
      // {icon: "cancer", tex: "\\cancer"},
      // {icon: "leo", tex: "\\leo"},
      // {icon: "virgo", tex: "\\virgo"},
      // {icon: "libra", tex: "\\libra"},
      // {icon: "scorpio", tex: "\\scorpio"},
      // {icon: "sagittarius", tex: "\\sagittarius"},
      // {icon: "capricornus", tex: "\\capricornus"},
      // {icon: "aquarius", tex: "\\aquarius"},
      // {icon: "pisces", tex: "\\pisces"},
      // {icon: "APLbox", tex: "\\APLbox"},
      // {icon: "APLcomment", tex: "\\APLcomment"},
      // {icon: "APLdown", tex: "\\APLdown"},
      // {icon: "APLdownarrowbox", tex: "\\APLdownarrowbox"},
      // {icon: "APLinput", tex: "\\APLinput"},
      // {icon: "APLinv", tex: "\\APLinv"},
      // {icon: "APLleftarrowbox", tex: "\\APLleftarrowbox"},
      // {icon: "APLlog", tex: "\\APLlog"},
      // {icon: "APLrightarrowbox", tex: "\\APLrightarrowbox"},
      // {icon: "APLstar", tex: "\\APLstar"},
      // {icon: "APLup", tex: "\\APLup"},
      // {icon: "APLuparrowbox", tex: "\\APLuparrowbox"}
    ]
  }
];
