
import {IMathMenuItem} from "./Types";

export const mathMenuData: IMathMenuItem[] = [
  // Individual buttons
  {name: "subscript", icon: require("./images/sub.svg"), key: "_" },
  {name: "superscript", icon: require("./images/super.svg"), key: "^" },
  {name: "frac", icon: require("./images/frac.svg"), tex: "\\frac"},
  {name: "sum", icon: require("./images/sum.svg"), tex: "\\sum"},
  {name: "int", icon: require("./images/int.svg"), tex: "\\int"},
  {name: "prod", icon: require("./images/prod.svg"), tex: "\\prod"},

  {name: "sep", isSeparator: true},

  {name: "Insert matrix", icon: require("./images/matrix.svg"), special: "show_matrix_modal" },
  {name: "Insert cases environment", icon: require("./images/cases.svg"), tex: "\\cases"},

  {name: "Add row", icon: require("./images/tabular-feature_append-row.svg"), key: "\n", ctrlKey: true, disabled: "not_inside_matrix"},
  {name: "Add column", icon: require("./images/tabular-feature_append-column.svg"), key: "\n", ctrlKey: true, shiftKey: true, disabled: "not_inside_matrix"},
  {name: "Delete row", icon: require("./images/tabular-feature_delete-row.svg"), chord: "M-m w d", disabled: "not_inside_matrix"},
  {name: "Delete column", icon: require("./images/tabular-feature_delete-column.svg"), chord: "M-m c d", disabled: "not_inside_matrix"},

  {name: "sep", isSeparator: true},

  {name: "Insert ()", icon: require("./images/lparen_rparen.svg"), rawTex: "\\left( \\hole \\right)"},
  {name: "Insert {}", icon: require("./images/lbracket_rbracket.svg"), rawTex: "\\left[ \\hole \\right]"},
  {name: "Insert []", icon: require("./images/lbrace_rbrace.svg"), rawTex: "\\left\\{ \\hole \\right\\}"},

  {name: "sep", isSeparator: true},

  {
    name: "Roots",
    icon: require("./images/root.svg"),
    children: [
      {name: "Square root \\sqrt", icon: require("./images/sqrt.svg"), tex: "\\sqrt"},
      {name: "Other root \\root", icon: require("./images/root.svg"), tex: "\\Root"}
    ]
  },
  {
    name: "Spaces",
    icon: require("./images/space.svg"),
    type: "text",
    children: [
      { name: "Thin space  ", tex: "\\,"},
      { name: "Medium space  ", tex: "\\:"},
      { name: "Thick space  ", tex: "\\;"},
      { name: "Quadratin space", tex: "\\quad"},
      { name: "Double quadratin space", tex: "\\qquad"},
      { name: "Negative space", tex: "\\!"},
      { name: "Phantom", tex: "\\phantom"},
      { name: "Horizontal phantom", tex: "\\hphantom"},
      { name: "Vertical phantom", tex: "\\vphantom"},
      { name: "Smash", tex: "\\smash"},
      { name: "Top smash", tex: "\\smasht"},
      { name: "Bottom smash", tex: "\\smashb"},
      { name: "Left overlap", tex: "\\mathllap"},
      { name: "Center overlap", tex: "\\mathclap"},
      { name: "Right overlap", tex: "\\mathrlap"}
    ]
  },
  {
    name: "Fractions",
    icon: require("./images/frac-square.svg"),
    type: "text",
    children: [
      {name: "Standard", tex: "\\frac"},
      {name: "Nice fraction (3/4)", tex: "\\nicefrac"},
      {name: "Unit (km)", tex: "\\unitone"},
      {name: "Unit (864 m)", tex: "\\unittwo"},
      {name: "Unit frac", tex: "\\unitfrac"},
      {name: "Unit frac", tex: "\\unitfracthree"},
      {name: "Text frac", tex: "\\tfrac"},
      {name: "Display fraction", tex: "\\dfrac"},
      {name: "Continued frac", tex: "\\cfrac"},
      {name: "Continued frac", tex: "\\cfracleft"},
      {name: "Continued frac", tex: "\\cfracright"},
      {name: "Binomial", tex: "\\binom"},
      {name: "Text binomial", tex: "\\tbinom"},
      {name: "Display binomial", tex: "\\dbinom"}
    ]
  },
  {
    name: "Fonts",
    icon: require("./images/font.svg"),
    children: [
      {name: "Roman", tex: "\\mathrm", icon: require("./images/mathrm.svg")},
      {name: "Bold", tex: "\\mathbf", icon: require("./images/mathbf.svg")},
      {name: "Bold symbol", tex: "\\boldsymbol", icon: require("./images/boldsymbol.svg")},
      {name: "Sans serif", tex: "\\mathsf", icon: require("./images/mathsf.svg")},
      {name: "Italic", tex: "\\mathit", icon: require("./images/mathit.svg")},
      {name: "Typewriter", tex: "\\mathtt", icon: require("./images/mathtt.svg")},
      {name: "Blackboard", tex: "\\mathbb", icon: require("./images/mathbb.svg")},
      {name: "Fraktur", tex: "\\mathfrak", icon: require("./images/mathfrak.svg")},
      {name: "Calligraphic", tex: "\\mathcal", icon: require("./images/mathcal.svg")},
      {name: "Formal Script", tex: "\\mathscr", icon: require("./images/mathscr.svg")},
      {name: "Normal text mode", tex: "\\textrm", icon: require("./images/textrm.svg")}
    ]
  },
  {
    name: "Functions",
    icon: require("./images/functions.svg"),
    type: "text",
    children: [
      {name: "arccos", tex: "\\arccos"},
      {name: "arcsin", tex: "\\arcsin"},
      {name: "arctan", tex: "\\arctan"},
      {name: "arg", tex: "\\arg"},
      {name: "bmod", tex: "\\bmod"},
      {name: "cos", tex: "\\cos"},
      {name: "cosh", tex: "\\cosh"},
      {name: "cot", tex: "\\cot"},
      {name: "coth", tex: "\\coth"},
      {name: "csc", tex: "\\csc"},
      {name: "deg", tex: "\\deg"},
      {name: "det", tex: "\\det"},
      {name: "dim", tex: "\\dim"},
      {name: "exp", tex: "\\exp"},
      {name: "gcd", tex: "\\gcd"},
      {name: "hom", tex: "\\hom"},
      {name: "inf", tex: "\\inf"},
      {name: "ker", tex: "\\ker"},
      {name: "lg", tex: "\\lg"},
      {name: "lim", tex: "\\lim"},
      {name: "liminf", tex: "\\liminf"},
      {name: "limsup", tex: "\\limsup"},
      {name: "ln", tex: "\\ln"},
      {name: "log", tex: "\\log"},
      {name: "max", tex: "\\max"},
      {name: "min", tex: "\\min"},
      {name: "sec", tex: "\\sec"},
      {name: "sin", tex: "\\sin"},
      {name: "sinh", tex: "\\sinh"},
      {name: "sup", tex: "\\sup"},
      {name: "tan", tex: "\\tan"},
      {name: "tanh", tex: "\\tanh"},
      {name: "Pr", tex: "\\Pr"}
    ]
  },
  {
    name: "Frame Decorations",
    icon: require("./images/hat.svg"),
    children: [
      {name: "hat", tex: "\\hat", icon: require("./images/hat.svg")},
      {name: "tilde", tex: "\\tilde", icon: require("./images/tilde.svg")},
      {name: "bar", tex: "\\bar", icon: require("./images/bar.svg")},
      {name: "grave", tex: "\\grave", icon: require("./images/grave.svg")},
      {name: "dot", tex: "\\dot", icon: require("./images/dot.svg")},
      {name: "check", tex: "\\check", icon: require("./images/check.svg")},
      {name: "widehat", tex: "\\widehat", icon: require("./images/widehat.svg")},
      {name: "widetilde", tex: "\\widetilde", icon: require("./images/widetilde.svg")},
      {name: "utilde", tex: "\\utilde", icon: require("./images/utilde.svg")},
      {name: "vec", tex: "\\vec", icon: require("./images/vec.svg")},
      {name: "acute", tex: "\\acute", icon: require("./images/acute.svg")},
      {name: "ddot", tex: "\\ddot", icon: require("./images/ddot.svg")},
      {name: "dddot", tex: "\\dddot", icon: require("./images/dddot.svg")},
      {name: "ddddot", tex: "\\ddddot", icon: require("./images/ddddot.svg")},
      {name: "breve", tex: "\\breve", icon: require("./images/breve.svg")},
      {name: "mathring", tex: "\\mathring", icon: require("./images/mathring.svg")},
      {name: "overline", tex: "\\overline", icon: require("./images/overline.svg")},
      {name: "overbrace", tex: "\\overbrace", icon: require("./images/overbrace.svg")},
      {name: "overleftarrow", tex: "\\overleftarrow", icon: require("./images/overleftarrow.svg")},
      {name: "overrightarrow", tex: "\\overrightarrow", icon: require("./images/overrightarrow.svg")},
      {name: "overleftrightarrow", tex: "\\overleftrightarrow", icon: require("./images/overleftrightarrow.svg")},
      {name: "underline", tex: "\\underline", icon: require("./images/underline.svg")},
      {name: "underbrace", tex: "\\underbrace", icon: require("./images/underbrace.svg")},
      {name: "underleftarrow", tex: "\\underleftarrow", icon: require("./images/underleftarrow.svg")},
      {name: "underrightarrow", tex: "\\underrightarrow", icon: require("./images/underrightarrow.svg")},
      {name: "underleftrightarrow", tex: "\\underleftrightarrow", icon: require("./images/underleftrightarrow.svg")},
      {name: "cancel", tex: "\\cancel", icon: require("./images/cancel.svg")},
      {name: "bcancel", tex: "\\bcancel", icon: require("./images/bcancel.svg")},
      {name: "xcancel", tex: "\\xcancel", icon: require("./images/xcancel.svg")},
      {name: "cancelto", tex: "\\cancelto", icon: require("./images/cancelto.svg")},
      {name: "Insert left/right side scripts", tex: "\\sideset", icon: require("./images/sideset.svg")},
      {name: "Insert right side scripts", tex: "\\sidesetr", icon: require("./images/sidesetr.svg")},
      {name: "Insert left side scripts", tex: "\\sidesetl", icon: require("./images/sidesetl.svg")},
      {name: "Insert side scripts", tex: "\\sidesetn", icon: require("./images/sidesetn.svg")},
      {name: "overset", tex: "\\overset", icon: require("./images/overset.svg")},
      {name: "underset", tex: "\\underset", icon: require("./images/underset.svg")},
      {name: "stackrel", tex: "\\stackrel", icon: require("./images/stackrel.svg")},
      {name: "stackrelthree", tex: "\\stackrelthree", icon: require("./images/stackrelthree.svg")}
    ]
  },
  {
    name: "Big Operators",
    icon: require("./images/intop.svg"),
    children: [
      {name: "intop", tex: "\\intop", icon: require("./images/intop.svg")},
      {name: "int", tex: "\\int", icon: require("./images/int.svg")},
      {name: "iint", tex: "\\iint", icon: require("./images/iint.svg")},
      // {name: "iintop", tex: "\\iintop", icon: require("./images/iintop.svg")},
      {name: "iiint", tex: "\\iiint", icon: require("./images/iiint.svg")},
      // {name: "iiintop", tex: "\\iiintop", icon: require("./images/iiintop.svg")},
      {name: "iiiint", tex: "\\iiiint", icon: require("./images/iiiint.svg")},
      // {name: "iiiintop", tex: "\\iiiintop", icon: require("./images/iiiintop.svg")},
      // {name: "dotsint", tex: "\\dotsint", icon: require("./images/dotsint.svg")},
      // {name: "dotsintop", tex: "\\dotsintop", icon: require("./images/dotsintop.svg")},
      // {name: "idotsint", tex: "\\idotsint", icon: require("./images/idotsint.svg")},
      {name: "oint", tex: "\\oint", icon: require("./images/oint.svg")},
      // {name: "ointop", tex: "\\ointop", icon: require("./images/ointop.svg")},
      // {name: "oiint", tex: "\\oiint", icon: require("./images/oiint.svg")},
      // {name: "oiintop", tex: "\\oiintop", icon: require("./images/oiintop.svg")},
      // {name: "ointctrclockwiseop", tex: "\\ointctrclockwiseop", icon: require("./images/ointctrclockwiseop.svg")},
      // {name: "ointctrclockwise", tex: "\\ointctrclockwise", icon: require("./images/ointctrclockwise.svg")},
      // {name: "ointclockwiseop", tex: "\\ointclockwiseop", icon: require("./images/ointclockwiseop.svg")},
      // {name: "ointclockwise", tex: "\\ointclockwise", icon: require("./images/ointclockwise.svg")},
      // {name: "sqint", tex: "\\sqint", icon: require("./images/sqint.svg")},
      // {name: "sqintop", tex: "\\sqintop", icon: require("./images/sqintop.svg")},
      // {name: "sqiint", tex: "\\sqiint", icon: require("./images/sqiint.svg")},
      // {name: "sqiintop", tex: "\\sqiintop", icon: require("./images/sqiintop.svg")},
      // {name: "fint", tex: "\\fint", icon: require("./images/fint.svg")},
      // {name: "fintop", tex: "\\fintop", icon: require("./images/fintop.svg")},
      // {name: "landupint", tex: "\\landupint", icon: require("./images/landupint.svg")},
      // {name: "landupintop", tex: "\\landupintop", icon: require("./images/landupintop.svg")},
      // {name: "landdownint", tex: "\\landdownint", icon: require("./images/landdownint.svg")},
      // {name: "landdownintop", tex: "\\landdownintop", icon: require("./images/landdownintop.svg")},
      // {name: "varint", tex: "\\varint", icon: require("./images/varint.svg")},
      // {name: "varoint", tex: "\\varoint", icon: require("./images/varoint.svg")},
      // {name: "varoiint", tex: "\\varoiint", icon: require("./images/varoiint.svg")},
      // {name: "varoiintop", tex: "\\varoiintop", icon: require("./images/varoiintop.svg")},
      // {name: "varointclockwise", tex: "\\varointclockwise", icon: require("./images/varointclockwise.svg")},
      // {name: "varointclockwiseop", tex: "\\varointclockwiseop", icon: require("./images/varointclockwiseop.svg")},
      // {name: "varointctrclockwise", tex: "\\varointctrclockwise", icon: require("./images/varointctrclockwise.svg")},
      // {name: "varointctrclockwiseop", tex: "\\varointctrclockwiseop", icon: require("./images/varointctrclockwiseop.svg")},
      {name: "sum", tex: "\\sum", icon: require("./images/sum.svg")},
      {name: "prod", tex: "\\prod", icon: require("./images/prod.svg")},
      {name: "coprod", tex: "\\coprod", icon: require("./images/coprod.svg")},
      {name: "bigsqcup", tex: "\\bigsqcup", icon: require("./images/bigsqcup.svg")},
      {name: "bigotimes", tex: "\\bigotimes", icon: require("./images/bigotimes.svg")},
      {name: "bigodot", tex: "\\bigodot", icon: require("./images/bigodot.svg")},
      {name: "bigoplus", tex: "\\bigoplus", icon: require("./images/bigoplus.svg")},
      {name: "bigcap", tex: "\\bigcap", icon: require("./images/bigcap.svg")},
      {name: "bigcup", tex: "\\bigcup", icon: require("./images/bigcup.svg")},
      {name: "biguplus", tex: "\\biguplus", icon: require("./images/biguplus.svg")},
      {name: "bigvee", tex: "\\bigvee", icon: require("./images/bigvee.svg")},
      {name: "bigwedge", tex: "\\bigwedge", icon: require("./images/bigwedge.svg")}
    ]
  },
  {
    name: "Miscellaneous",
    icon: require("./images/nabla.svg"),
    children: [
      {icon: require("./images/nabla.svg"), tex: "\\nabla"},
      {icon: require("./images/partial.svg"), tex: "\\partial"},
      {icon: require("./images/infty.svg"), tex: "\\infty"},
      {icon: require("./images/prime.svg"), tex: "\\prime"},
      {icon: require("./images/ell.svg"), tex: "\\ell"},
      {icon: require("./images/emptyset.svg"), tex: "\\emptyset"},
      {icon: require("./images/exists.svg"), tex: "\\exists"},
      {icon: require("./images/forall.svg"), tex: "\\forall"},
      {icon: require("./images/imath.svg"), tex: "\\imath"},
      {icon: require("./images/jmath.svg"), tex: "\\jmath"},
      {icon: require("./images/Re.svg"), tex: "\\Re"},
      {icon: require("./images/Im.svg"), tex: "\\Im"},
      {icon: require("./images/aleph.svg"), tex: "\\aleph"},
      {icon: require("./images/wp.svg"), tex: "\\wp"},
      {icon: require("./images/hbar.svg"), tex: "\\hbar"},
      {icon: require("./images/angle.svg"), tex: "\\angle"},
      {icon: require("./images/top.svg"), tex: "\\top"},
      {icon: require("./images/bot.svg"), tex: "\\bot"},
      {icon: require("./images/vert2.svg"), tex: "\\Vert"},
      {icon: require("./images/neg.svg"), tex: "\\neg"},
      {icon: require("./images/flat.svg"), tex: "\\flat"},
      {icon: require("./images/natural.svg"), tex: "\\natural"},
      {icon: require("./images/sharp.svg"), tex: "\\sharp"},
      {icon: require("./images/surd.svg"), tex: "\\surd"},
      // {icon: require("./images/lhook.svg"), tex: "\\lhook"},
      // {icon: require("./images/rhook.svg"), tex: "\\rhook"},
      {icon: require("./images/triangle.svg"), tex: "\\triangle"},
      {icon: require("./images/diamondsuit.svg"), tex: "\\diamondsuit"},
      {icon: require("./images/heartsuit.svg"), tex: "\\heartsuit"},
      {icon: require("./images/clubsuit.svg"), tex: "\\clubsuit"},
      {icon: require("./images/spadesuit.svg"), tex: "\\spadesuit"},
      // {icon: "textrm \\AA", tex: "\\textrm \AA"},
      // {icon: "textrm \\O", tex: "\\textrm \O"},
      // {icon: "mathcircumflex", tex: "\\mathcircumflex"},
      // {icon: "_", tex: "\\_"},
      // {icon: "textdegree", tex: "\\textdegree"},
      // {icon: "mathdollar", tex: "\\mathdollar"},
      // {icon: "mathparagraph", tex: "\\mathparagraph"},
      // {icon: "mathsection", tex: "\\mathsection"},
      // {icon: "mathrm T", tex: "\\mathrm T"},
      // {icon: "mathbb N", tex: "\\mathbb N"},
      // {icon: "mathbb Z", tex: "\\mathbb Z"},
      // {icon: "mathbb Q", tex: "\\mathbb Q"},
      // {icon: "mathbb R", tex: "\\mathbb R"},
      // {icon: "mathbb C", tex: "\\mathbb C"},
      // {icon: "mathbb H", tex: "\\mathbb H"},
      // {icon: "mathcal F", tex: "\\mathcal F"},
      // {icon: "mathcal L", tex: "\\mathcal L"},
      // {icon: "mathcal H", tex: "\\mathcal H"},
      // {icon: "mathcal O", tex: "\\mathcal O"}
    ]
  },
  {
    name: "Greek",
    icon: require("./images/alpha.svg"),
    children: [
      { name: "alpha", tex: "\\alpha", icon: require("./images/alpha.svg") },
      { name: "beta", tex: "\\beta", icon: require("./images/beta.svg") },
      { name: "gamma", tex: "\\gamma", icon: require("./images/gamma.svg") },
      { name: "delta", tex: "\\delta", icon: require("./images/delta.svg") },
      { name: "epsilon", tex: "\\epsilon", icon: require("./images/epsilon.svg") },
      { name: "varepsilon", tex: "\\varepsilon", icon: require("./images/varepsilon.svg") },
      { name: "zeta", tex: "\\zeta", icon: require("./images/zeta.svg") },
      { name: "eta", tex: "\\eta", icon: require("./images/eta.svg") },
      { name: "theta", tex: "\\theta", icon: require("./images/theta.svg") },
      { name: "vartheta", tex: "\\vartheta", icon: require("./images/vartheta.svg") },
      { name: "iota", tex: "\\iota", icon: require("./images/iota.svg") },
      { name: "kappa", tex: "\\kappa", icon: require("./images/kappa.svg") },
      { name: "lambda", tex: "\\lambda", icon: require("./images/lambda.svg") },
      { name: "mu", tex: "\\mu", icon: require("./images/mu.svg") },
      { name: "nu", tex: "\\nu", icon: require("./images/nu.svg") },
      { name: "xi", tex: "\\xi", icon: require("./images/xi.svg") },
      { name: "pi", tex: "\\pi", icon: require("./images/pi.svg") },
      { name: "varpi", tex: "\\varpi", icon: require("./images/varpi.svg") },
      { name: "rho", tex: "\\rho", icon: require("./images/rho.svg") },
      { name: "varrho", tex: "\\varrho", icon: require("./images/varrho.svg") },
      { name: "sigma", tex: "\\sigma", icon: require("./images/sigma.svg") },
      { name: "varsigma", tex: "\\varsigma", icon: require("./images/varsigma.svg") },
      { name: "tau", tex: "\\tau", icon: require("./images/tau.svg") },
      { name: "upsilon", tex: "\\upsilon", icon: require("./images/upsilon.svg") },
      { name: "phi", tex: "\\phi", icon: require("./images/phi.svg") },
      { name: "varphi", tex: "\\varphi", icon: require("./images/varphi.svg") },
      { name: "chi", tex: "\\chi", icon: require("./images/chi.svg") },
      { name: "psi", tex: "\\psi", icon: require("./images/psi.svg") },
      { name: "omega", tex: "\\omega", icon: require("./images/omega.svg") },
      { name: "Gamma", tex: "\\Gamma", icon: require("./images/gamma2.svg") },
      { name: "Delta", tex: "\\Delta", icon: require("./images/delta2.svg") },
      { name: "Theta", tex: "\\Theta", icon: require("./images/theta2.svg") },
      { name: "Lambda", tex: "\\Lambda", icon: require("./images/lambda2.svg") },
      { name: "Xi", tex: "\\Xi", icon: require("./images/xi2.svg") },
      { name: "Pi", tex: "\\Pi", icon: require("./images/pi2.svg") },
      { name: "Sigma", tex: "\\Sigma", icon: require("./images/sigma2.svg") },
      { name: "Upsilon", tex: "\\Upsilon", icon: require("./images/upsilon2.svg") },
      { name: "Phi", tex: "\\Phi", icon: require("./images/phi2.svg") },
      { name: "Psi", tex: "\\Psi", icon: require("./images/psi2.svg") },
      { name: "Omega", tex: "\\Omega", icon: require("./images/omega2.svg") },
      { name: "varGamma", tex: "\\varGamma", icon: require("./images/vargamma2.svg") },
      { name: "varDelta", tex: "\\varDelta", icon: require("./images/vardelta2.svg") },
      { name: "varTheta", tex: "\\varTheta", icon: require("./images/vartheta2.svg") },
      { name: "varLambda", tex: "\\varLambda", icon: require("./images/varlambda2.svg") },
      { name: "varXi", tex: "\\varXi", icon: require("./images/varxi2.svg") },
      { name: "varPi", tex: "\\varPi", icon: require("./images/varpi2.svg") },
      { name: "varSigma", tex: "\\varSigma", icon: require("./images/varsigma2.svg") },
      { name: "varUpsilon", tex: "\\varUpsilon", icon: require("./images/varupsilon2.svg") },
      { name: "varPhi", tex: "\\varPhi", icon: require("./images/varphi2.svg") },
      { name: "varPsi", tex: "\\varPsi", icon: require("./images/varpsi2.svg") },
      { name: "varOmega", tex: "\\varOmega", icon: require("./images/varomega2.svg") }
    ]
  },
  {
    name: "Arrows",
    icon: require("./images/leftarrow.svg"),
    children: [
      {icon: require("./images/leftarrow.svg"), tex: "\\leftarrow"},
      {icon: require("./images/rightarrow.svg"), tex: "\\rightarrow"},
      {icon: require("./images/downarrow.svg"), tex: "\\downarrow"},
      {icon: require("./images/uparrow.svg"), tex: "\\uparrow"},
      {icon: require("./images/updownarrow.svg"), tex: "\\updownarrow"},
      {icon: require("./images/leftrightarrow.svg"), tex: "\\leftrightarrow"},
      {icon: require("./images/leftarrow2.svg"), tex: "\\Leftarrow"},
      {icon: require("./images/rightarrow2.svg"), tex: "\\Rightarrow"},
      {icon: require("./images/downarrow2.svg"), tex: "\\Downarrow"},
      {icon: require("./images/uparrow2.svg"), tex: "\\Uparrow"},
      {icon: require("./images/updownarrow2.svg"), tex: "\\Updownarrow"},
      {icon: require("./images/leftrightarrow2.svg"), tex: "\\Leftrightarrow"},
      {icon: require("./images/longleftrightarrow2.svg"), tex: "\\Longleftrightarrow"},
      {icon: require("./images/longleftarrow2.svg"), tex: "\\Longleftarrow"},
      {icon: require("./images/longrightarrow2.svg"), tex: "\\Longrightarrow"},
      {icon: require("./images/longleftrightarrow.svg"), tex: "\\longleftrightarrow"},
      {icon: require("./images/longleftarrow.svg"), tex: "\\longleftarrow"},
      {icon: require("./images/longrightarrow.svg"), tex: "\\longrightarrow"},
      {icon: require("./images/leftharpoondown.svg"), tex: "\\leftharpoondown"},
      {icon: require("./images/rightharpoondown.svg"), tex: "\\rightharpoondown"},
      {icon: require("./images/mapsto.svg"), tex: "\\mapsto"},
      {icon: require("./images/longmapsto.svg"), tex: "\\longmapsto"},
      {icon: require("./images/nwarrow.svg"), tex: "\\nwarrow"},
      {icon: require("./images/nearrow.svg"), tex: "\\nearrow"},
      {icon: require("./images/leftharpoonup.svg"), tex: "\\leftharpoonup"},
      {icon: require("./images/rightharpoonup.svg"), tex: "\\rightharpoonup"},
      {icon: require("./images/hookleftarrow.svg"), tex: "\\hookleftarrow"},
      {icon: require("./images/hookrightarrow.svg"), tex: "\\hookrightarrow"},
      {icon: require("./images/swarrow.svg"), tex: "\\swarrow"},
      {icon: require("./images/searrow.svg"), tex: "\\searrow"},
      {icon: require("./images/rightleftharpoons.svg"), tex: "\\rightleftharpoons"}
    ]
  },
  {
    name: "Arrows (extended)",
    icon: require("./images/dashleftarrow.svg"),
    children: [
      {icon: require("./images/dashleftarrow.svg"), tex: "\\dashleftarrow"},
      {icon: require("./images/dashrightarrow.svg"), tex: "\\dashrightarrow"},
      {icon: require("./images/leftleftarrows.svg"), tex: "\\leftleftarrows"},
      {icon: require("./images/leftrightarrows.svg"), tex: "\\leftrightarrows"},
      {icon: require("./images/rightrightarrows.svg"), tex: "\\rightrightarrows"},
      {icon: require("./images/rightleftarrows.svg"), tex: "\\rightleftarrows"},
      {icon: require("./images/Lleftarrow.svg"), tex: "\\Lleftarrow"},
      {icon: require("./images/Rrightarrow.svg"), tex: "\\Rrightarrow"},
      {icon: require("./images/twoheadleftarrow.svg"), tex: "\\twoheadleftarrow"},
      {icon: require("./images/twoheadrightarrow.svg"), tex: "\\twoheadrightarrow"},
      {icon: require("./images/leftarrowtail.svg"), tex: "\\leftarrowtail"},
      {icon: require("./images/rightarrowtail.svg"), tex: "\\rightarrowtail"},
      {icon: require("./images/looparrowleft.svg"), tex: "\\looparrowleft"},
      {icon: require("./images/looparrowright.svg"), tex: "\\looparrowright"},
      {icon: require("./images/curvearrowleft.svg"), tex: "\\curvearrowleft"},
      {icon: require("./images/curvearrowright.svg"), tex: "\\curvearrowright"},
      {icon: require("./images/circlearrowleft.svg"), tex: "\\circlearrowleft"},
      {icon: require("./images/circlearrowright.svg"), tex: "\\circlearrowright"},
      {icon: require("./images/Lsh.svg"), tex: "\\Lsh"},
      {icon: require("./images/Rsh.svg"), tex: "\\Rsh"},
      {icon: require("./images/upuparrows.svg"), tex: "\\upuparrows"},
      {icon: require("./images/downdownarrows.svg"), tex: "\\downdownarrows"},
      {icon: require("./images/upharpoonleft.svg"), tex: "\\upharpoonleft"},
      {icon: require("./images/upharpoonright.svg"), tex: "\\upharpoonright"},
      {icon: require("./images/downharpoonleft.svg"), tex: "\\downharpoonleft"},
      {icon: require("./images/downharpoonright.svg"), tex: "\\downharpoonright"},
      {icon: require("./images/leftrightharpoons.svg"), tex: "\\leftrightharpoons"},
      {icon: require("./images/rightleftharpoons.svg"), tex: "\\rightleftharpoons"},
      {icon: require("./images/rightsquigarrow.svg"), tex: "\\rightsquigarrow"},
      {icon: require("./images/leftrightsquigarrow.svg"), tex: "\\leftrightsquigarrow"},
      {icon: require("./images/nleftarrow.svg"), tex: "\\nleftarrow"},
      {icon: require("./images/nrightarrow.svg"), tex: "\\nrightarrow"},
      {icon: require("./images/nleftrightarrow.svg"), tex: "\\nleftrightarrow"},
      {icon: require("./images/nleftarrow2.svg"), tex: "\\nLeftarrow"},
      {icon: require("./images/nrightarrow2.svg"), tex: "\\nRightarrow"},
      {icon: require("./images/nleftrightarrow2.svg"), tex: "\\nLeftrightarrow"},
      {icon: require("./images/multimap.svg"), tex: "\\multimap"},
      // {icon: require("./images/shortleftarrow.svg"), tex: "\\shortleftarrow"},
      // {icon: require("./images/shortrightarrow.svg"), tex: "\\shortrightarrow"},
      // {icon: require("./images/shortuparrow.svg"), tex: "\\shortuparrow"},
      // {icon: require("./images/shortdownarrow.svg"), tex: "\\shortdownarrow"},
      // {icon: require("./images/leftrightarroweq.svg"), tex: "\\leftrightarroweq"},
      // {icon: require("./images/curlyveedownarrow.svg"), tex: "\\curlyveedownarrow"},
      // {icon: require("./images/curlyveeuparrow.svg"), tex: "\\curlyveeuparrow"},
      // {icon: require("./images/nnwarrow.svg"), tex: "\\nnwarrow"},
      // {icon: require("./images/nnearrow.svg"), tex: "\\nnearrow"},
      // {icon: require("./images/sswarrow.svg"), tex: "\\sswarrow"},
      // {icon: require("./images/ssearrow.svg"), tex: "\\ssearrow"},
      // {icon: require("./images/curlywedgeuparrow.svg"), tex: "\\curlywedgeuparrow"},
      // {icon: require("./images/curlywedgedownarrow.svg"), tex: "\\curlywedgedownarrow"},
      // {icon: require("./images/leftrightarrowtriangle.svg"), tex: "\\leftrightarrowtriangle"},
      // {icon: require("./images/leftarrowtriangle.svg"), tex: "\\leftarrowtriangle"},
      // {icon: require("./images/rightarrowtriangle.svg"), tex: "\\rightarrowtriangle"},
      // {icon: require("./images/mapsto2.svg"), tex: "\\Mapsto"},
      // {icon: require("./images/mapsfrom.svg"), tex: "\\mapsfrom"},
      // {icon: require("./images/mapsfrom2.svg"), tex: "\\Mapsfrom"},
      // {icon: require("./images/longmapsto2.svg"), tex: "\\Longmapsto"},
      // {icon: require("./images/longmapsfrom.svg"), tex: "\\longmapsfrom"},
      // {icon: require("./images/longmapsfrom2.svg"), tex: "\\Longmapsfrom"},
      {icon: require("./images/xleftarrow.svg"), tex: "\\xleftarrow"},
      {icon: require("./images/xrightarrow.svg"), tex: "\\xrightarrow"}
    ]
  },
  {
    name: "Operators",
    icon: require("./images/pm.svg"),
    children: [
      {name: "pm", tex: "\\pm", icon: require("./images/pm.svg")},
      {name: "cap", tex: "\\cap", icon: require("./images/cap.svg")},
      {name: "diamond", tex: "\\diamond", icon: require("./images/diamond.svg")},
      {name: "oplus", tex: "\\oplus", icon: require("./images/oplus.svg")},
      {name: "mp", tex: "\\mp", icon: require("./images/mp.svg")},
      {name: "cup", tex: "\\cup", icon: require("./images/cup.svg")},
      {name: "bigtriangleup", tex: "\\bigtriangleup", icon: require("./images/bigtriangleup.svg")},
      {name: "ominus", tex: "\\ominus", icon: require("./images/ominus.svg")},
      {name: "times", tex: "\\times", icon: require("./images/times.svg")},
      {name: "uplus", tex: "\\uplus", icon: require("./images/uplus.svg")},
      {name: "bigtriangledown", tex: "\\bigtriangledown", icon: require("./images/bigtriangledown.svg")},
      {name: "otimes", tex: "\\otimes", icon: require("./images/otimes.svg")},
      {name: "div", tex: "\\div", icon: require("./images/div.svg")},
      {name: "sqcap", tex: "\\sqcap", icon: require("./images/sqcap.svg")},
      {name: "triangleright", tex: "\\triangleright", icon: require("./images/triangleright.svg")},
      {name: "oslash", tex: "\\oslash", icon: require("./images/oslash.svg")},
      {name: "cdot", tex: "\\cdot", icon: require("./images/cdot.svg")},
      {name: "sqcup", tex: "\\sqcup", icon: require("./images/sqcup.svg")},
      {name: "triangleleft", tex: "\\triangleleft", icon: require("./images/triangleleft.svg")},
      {name: "odot", tex: "\\odot", icon: require("./images/odot.svg")},
      {name: "star", tex: "\\star", icon: require("./images/star.svg")},
      {name: "ast", tex: "\\ast", icon: require("./images/ast.svg")},
      {name: "vee", tex: "\\vee", icon: require("./images/vee.svg")},
      {name: "amalg", tex: "\\amalg", icon: require("./images/amalg.svg")},
      {name: "bigcirc", tex: "\\bigcirc", icon: require("./images/bigcirc.svg")},
      {name: "setminus", tex: "\\setminus", icon: require("./images/setminus.svg")},
      {name: "wedge", tex: "\\wedge", icon: require("./images/wedge.svg")},
      {name: "dagger", tex: "\\dagger", icon: require("./images/dagger.svg")},
      {name: "circ", tex: "\\circ", icon: require("./images/circ.svg")},
      {name: "bullet", tex: "\\bullet", icon: require("./images/bullet.svg")},
      {name: "wr", tex: "\\wr", icon: require("./images/wr.svg")},
      {name: "ddagger", tex: "\\ddagger", icon: require("./images/ddagger.svg")},
      {name: "smallint", tex: "\\smallint", icon: require("./images/smallint.svg")}
    ]
  },
  {
    name: "Operators (extended)",
    icon: require("./images/dotplus.svg"),
    children: [
      {icon: require("./images/dotplus.svg"), tex: "\\dotplus"},
      {icon: require("./images/smallsetminus.svg"), tex: "\\smallsetminus"},
      {icon: require("./images/cap2.svg"), tex: "\\Cap"},
      {icon: require("./images/cup2.svg"), tex: "\\Cup"},
      {icon: require("./images/barwedge.svg"), tex: "\\barwedge"},
      {icon: require("./images/veebar.svg"), tex: "\\veebar"},
      {icon: require("./images/doublebarwedge.svg"), tex: "\\doublebarwedge"},
      {icon: require("./images/boxminus.svg"), tex: "\\boxminus"},
      {icon: require("./images/boxtimes.svg"), tex: "\\boxtimes"},
      {icon: require("./images/boxdot.svg"), tex: "\\boxdot"},
      {icon: require("./images/boxplus.svg"), tex: "\\boxplus"},
      // {icorequire("./images/n"): boxastrequire, tex: "\\boxast"},
      // {icon: boxbarrequire, tex: "\\boxbar"},
      // {icon: boxslashrequire, tex: "\\boxslash"},
      // {icon: boxbslashrequire, tex: "\\boxbslash"},
      // {icon: boxcirclerequire, tex: "\\boxcircle"},
      // {icon: boxboxrequire, tex: "\\boxbox"},
      // {icon: boxemptyrequire, tex: "\\boxempty"},
      {icon: require("./images/divideontimes.svg"), tex: "\\divideontimes"},
      {icon: require("./images/ltimes.svg"), tex: "\\ltimes"},
      {icon: require("./images/rtimes.svg"), tex: "\\rtimes"},
      {icon: require("./images/leftthreetimes.svg"), tex: "\\leftthreetimes"},
      {icon: require("./images/rightthreetimes.svg"), tex: "\\rightthreetimes"},
      {icon: require("./images/curlywedge.svg"), tex: "\\curlywedge"},
      {icon: require("./images/curlyvee.svg"), tex: "\\curlyvee"},
      {icon: require("./images/circleddash.svg"), tex: "\\circleddash"},
      {icon: require("./images/circledast.svg"), tex: "\\circledast"},
      {icon: require("./images/circledcirc.svg"), tex: "\\circledcirc"},
      {icon: require("./images/centerdot.svg"), tex: "\\centerdot"},
      {icon: require("./images/intercal.svg"), tex: "\\intercal"},
      {icon: require("./images/implies.svg"), tex: "\\implies"},
      {icon: require("./images/impliedby.svg"), tex: "\\impliedby"},
      // {icon: bigcurlyveerequire, tex: "\\bigcurlyvee"},
      // {icon: bigcurlywedgerequire, tex: "\\bigcurlywedge"},
      // {icon: bigsqcaprequire, tex: "\\bigsqcap"},
      // {icon: bigboxrequire, tex: "\\bigbox"},
      // {icon: bigparallelrequire, tex: "\\bigparallel"},
      // {icon: biginterleaverequire, tex: "\\biginterleave"},
      // {icon: bignplusrequire, tex: "\\bignplus"},
      // {icon: nplusrequire, tex: "\\nplus"},
      // {icon: Yuprequire, tex: "\\Yup"},
      // {icon: Ydownrequire, tex: "\\Ydown"},
      // {icon: Yleftrequire, tex: "\\Yleft"},
      // {icon: Yrightrequire, tex: "\\Yright"},
      // {icon: obarrequire, tex: "\\obar"},
      // {icon: obslashrequire, tex: "\\obslash"},
      // {icon: ocirclerequire, tex: "\\ocircle"},
      // {icon: olessthanrequire, tex: "\\olessthan"},
      // {icon: ogreaterthanrequire, tex: "\\ogreaterthan"},
      // {icon: oveerequire, tex: "\\ovee"},
      // {icon: owedgerequire, tex: "\\owedge"},
      // {icon: varcurlyveerequire, tex: "\\varcurlyvee"},
      // {icon: varcurlywedgerequire, tex: "\\varcurlywedge"},
      // {icon: vartimesrequire, tex: "\\vartimes"},
      // {icon: varotimesrequire, tex: "\\varotimes"},
      // {icon: varoastrequire, tex: "\\varoast"},
      // {icon: varobarrequire, tex: "\\varobar"},
      // {icon: varodotrequire, tex: "\\varodot"},
      // {icon: varoslashrequire, tex: "\\varoslash"},
      // {icon: varobslashrequire, tex: "\\varobslash"},
      // {icon: varocirclerequire, tex: "\\varocircle"},
      // {icon: varoplusrequire, tex: "\\varoplus"},
      // {icon: varominusrequire, tex: "\\varominus"},
      // {icon: varoveerequire, tex: "\\varovee"},
      // {icon: varowedgerequire, tex: "\\varowedge"},
      // {icon: varolessthanrequire, tex: "\\varolessthan"},
      // {icon: varogreaterthanrequire, tex: "\\varogreaterthan"},
      // {icon: varbigcircrequire, tex: "\\varbigcirc"}
    ]
  },
  {
    name: "Relations",
    icon: require("./images/leq.svg"),
    children: [
      {icon: require("./images/leq.svg"),  tex: "\\leq"},
      {icon: require("./images/geq.svg"),  tex: "\\geq"},
      {icon: require("./images/equiv.svg"),  tex: "\\equiv"},
      {icon: require("./images/models.svg"),  tex: "\\models"},
      {icon: require("./images/prec.svg"),  tex: "\\prec"},
      {icon: require("./images/succ.svg"),  tex: "\\succ"},
      {icon: require("./images/sim.svg"),  tex: "\\sim"},
      {icon: require("./images/perp.svg"),  tex: "\\perp"},
      {icon: require("./images/preceq.svg"),  tex: "\\preceq"},
      {icon: require("./images/succeq.svg"),  tex: "\\succeq"},
      {icon: require("./images/simeq.svg"),  tex: "\\simeq"},
      {icon: require("./images/mid.svg"),  tex: "\\mid"},
      {icon: require("./images/ll.svg"),  tex: "\\ll"},
      {icon: require("./images/gg.svg"),  tex: "\\gg"},
      {icon: require("./images/asymp.svg"),  tex: "\\asymp"},
      {icon: require("./images/parallel.svg"),  tex: "\\parallel"},
      {icon: require("./images/subset.svg"),  tex: "\\subset"},
      {icon: require("./images/supset.svg"),  tex: "\\supset"},
      {icon: require("./images/approx.svg"),  tex: "\\approx"},
      {icon: require("./images/smile.svg"),  tex: "\\smile"},
      {icon: require("./images/subseteq.svg"),  tex: "\\subseteq"},
      {icon: require("./images/supseteq.svg"),  tex: "\\supseteq"},
      {icon: require("./images/cong.svg"),  tex: "\\cong"},
      {icon: require("./images/frown.svg"),  tex: "\\frown"},
      {icon: require("./images/sqsubseteq.svg"),  tex: "\\sqsubseteq"},
      {icon: require("./images/sqsupseteq.svg"),  tex: "\\sqsupseteq"},
      {icon: require("./images/doteq.svg"),  tex: "\\doteq"},
      {icon: require("./images/neq.svg"),  tex: "\\neq"},
      {icon: require("./images/in.svg"), tex: "\\in"},
      {icon: require("./images/ni.svg"), tex: "\\ni"},
      {icon: require("./images/propto.svg"), tex: "\\propto"},
      {icon: require("./images/notin.svg"), tex: "\\notin"},
      {icon: require("./images/vdash.svg"), tex: "\\vdash"},
      {icon: require("./images/dashv.svg"), tex: "\\dashv"},
      {icon: require("./images/bowtie.svg"), tex: "\\bowtie"},
      {icon: require("./images/iff.svg"), tex: "\\iff"},
      {icon: require("./images/not.svg"), tex: "\\not"},
      {icon: require("./images/land.svg"), tex: "\\land"},
      {icon: require("./images/lor.svg"), tex: "\\lor"},
      {icon: require("./images/lnot.svg"), tex: "\\lnot"}
    ]
  },

  {
    name: "Relations (extended)",
    icon: require("./images/leqq.svg"),
    children: [
      {icon: require("./images/leqq.svg"), tex: "\\leqq"},
      {icon: require("./images/geqq.svg"), tex: "\\geqq"},
      {icon: require("./images/leqslant.svg"), tex: "\\leqslant"},
      {icon: require("./images/geqslant.svg"), tex: "\\geqslant"},
      {icon: require("./images/eqslantless.svg"), tex: "\\eqslantless"},
      {icon: require("./images/eqslantgtr.svg"), tex: "\\eqslantgtr"},
      {icon: require("./images/eqsim.svg"), tex: "\\eqsim"},
      {icon: require("./images/lesssim.svg"), tex: "\\lesssim"},
      {icon: require("./images/gtrsim.svg"), tex: "\\gtrsim"},
      {icon: require("./images/apprge.svg"), tex: "\\apprge"},
      {icon: require("./images/apprle.svg"), tex: "\\apprle"},
      {icon: require("./images/lessapprox.svg"), tex: "\\lessapprox"},
      {icon: require("./images/gtrapprox.svg"), tex: "\\gtrapprox"},
      {icon: require("./images/approxeq.svg"), tex: "\\approxeq"},
      {icon: require("./images/triangleq.svg"), tex: "\\triangleq"},
      {icon: require("./images/lessdot.svg"), tex: "\\lessdot"},
      {icon: require("./images/gtrdot.svg"), tex: "\\gtrdot"},
      {icon: require("./images/lll.svg"), tex: "\\lll"},
      {icon: require("./images/ggg.svg"), tex: "\\ggg"},
      {icon: require("./images/lessgtr.svg"), tex: "\\lessgtr"},
      {icon: require("./images/gtrless.svg"), tex: "\\gtrless"},
      {icon: require("./images/lesseqgtr.svg"), tex: "\\lesseqgtr"},
      {icon: require("./images/gtreqless.svg"), tex: "\\gtreqless"},
      {icon: require("./images/lesseqqgtr.svg"), tex: "\\lesseqqgtr"},
      {icon: require("./images/gtreqqless.svg"), tex: "\\gtreqqless"},
      {icon: require("./images/eqcirc.svg"), tex: "\\eqcirc"},
      {icon: require("./images/circeq.svg"), tex: "\\circeq"},
      {icon: require("./images/thicksim.svg"), tex: "\\thicksim"},
      {icon: require("./images/thickapprox.svg"), tex: "\\thickapprox"},
      {icon: require("./images/backsim.svg"), tex: "\\backsim"},
      {icon: require("./images/backsimeq.svg"), tex: "\\backsimeq"},
      {icon: require("./images/subseteqq.svg"), tex: "\\subseteqq"},
      {icon: require("./images/supseteqq.svg"), tex: "\\supseteqq"},
      {icon: require("./images/subset2.svg"), tex: "\\Subset"},
      {icon: require("./images/supset2.svg"), tex: "\\Supset"},
      {icon: require("./images/sqsubset.svg"), tex: "\\sqsubset"},
      {icon: require("./images/sqsupset.svg"), tex: "\\sqsupset"},
      {icon: require("./images/preccurlyeq.svg"), tex: "\\preccurlyeq"},
      {icon: require("./images/succcurlyeq.svg"), tex: "\\succcurlyeq"},
      {icon: require("./images/curlyeqprec.svg"), tex: "\\curlyeqprec"},
      {icon: require("./images/curlyeqsucc.svg"), tex: "\\curlyeqsucc"},
      {icon: require("./images/precsim.svg"), tex: "\\precsim"},
      {icon: require("./images/succsim.svg"), tex: "\\succsim"},
      {icon: require("./images/precapprox.svg"), tex: "\\precapprox"},
      {icon: require("./images/succapprox.svg"), tex: "\\succapprox"},
      {icon: require("./images/vartriangleleft.svg"), tex: "\\vartriangleleft"},
      {icon: require("./images/vartriangleright.svg"), tex: "\\vartriangleright"},
      {icon: require("./images/trianglelefteq.svg"), tex: "\\trianglelefteq"},
      {icon: require("./images/trianglerighteq.svg"), tex: "\\trianglerighteq"},
      {icon: require("./images/bumpeq.svg"), tex: "\\bumpeq"},
      {icon: require("./images/bumpeq2.svg"), tex: "\\Bumpeq"},
      {icon: require("./images/doteqdot.svg"), tex: "\\doteqdot"},
      {icon: require("./images/risingdotseq.svg"), tex: "\\risingdotseq"},
      {icon: require("./images/fallingdotseq.svg"), tex: "\\fallingdotseq"},
      {icon: require("./images/vdash2.svg"), tex: "\\vDash"},
      {icon: require("./images/Vvdash.svg"), tex: "\\Vvdash"},
      {icon: require("./images/vdash3.svg"), tex: "\\Vdash"},
      {icon: require("./images/shortmid.svg"), tex: "\\shortmid"},
      {icon: require("./images/shortparallel.svg"), tex: "\\shortparallel"},
      {icon: require("./images/smallsmile.svg"), tex: "\\smallsmile"},
      {icon: require("./images/smallfrown.svg"), tex: "\\smallfrown"},
      {icon: require("./images/blacktriangleleft.svg"), tex: "\\blacktriangleleft"},
      {icon: require("./images/blacktriangleright.svg"), tex: "\\blacktriangleright"},
      {icon: require("./images/because.svg"), tex: "\\because"},
      {icon: require("./images/therefore.svg"), tex: "\\therefore"},
      {icon: require("./images/wasytherefore.svg"), tex: "\\wasytherefore"},
      {icon: require("./images/backepsilon.svg"), tex: "\\backepsilon"},
      {icon: require("./images/varpropto.svg"), tex: "\\varpropto"},
      {icon: require("./images/between.svg"), tex: "\\between"},
      {icon: require("./images/pitchfork.svg"), tex: "\\pitchfork"},
      {icon: require("./images/trianglelefteqslant.svg"), tex: "\\trianglelefteqslant"},
      {icon: require("./images/trianglerighteqslant.svg"), tex: "\\trianglerighteqslant"},
      {icon: require("./images/inplus.svg"), tex: "\\inplus"},
      {icon: require("./images/niplus.svg"), tex: "\\niplus"},
      {icon: require("./images/subsetplus.svg"), tex: "\\subsetplus"},
      {icon: require("./images/supsetplus.svg"), tex: "\\supsetplus"},
      {icon: require("./images/subsetpluseq.svg"), tex: "\\subsetpluseq"},
      {icon: require("./images/supsetpluseq.svg"), tex: "\\supsetpluseq"},
      {icon: require("./images/minuso.svg"), tex: "\\minuso"},
      {icon: require("./images/baro.svg"), tex: "\\baro"},
      {icon: require("./images/sslash.svg"), tex: "\\sslash"},
      {icon: require("./images/bbslash.svg"), tex: "\\bbslash"},
      {icon: require("./images/moo.svg"), tex: "\\moo"},
      {icon: require("./images/merge.svg"), tex: "\\merge"},
      {icon: require("./images/invneg.svg"), tex: "\\invneg"},
      {icon: require("./images/lbag.svg"), tex: "\\lbag"},
      {icon: require("./images/rbag.svg"), tex: "\\rbag"},
      {icon: require("./images/interleave.svg"), tex: "\\interleave"},
      {icon: require("./images/leftslice.svg"), tex: "\\leftslice"},
      {icon: require("./images/rightslice.svg"), tex: "\\rightslice"},
      {icon: require("./images/oblong.svg"), tex: "\\oblong"},
      {icon: require("./images/talloblong.svg"), tex: "\\talloblong"},
      {icon: require("./images/fatsemi.svg"), tex: "\\fatsemi"},
      {icon: require("./images/fatslash.svg"), tex: "\\fatslash"},
      {icon: require("./images/fatbslash.svg"), tex: "\\fatbslash"},
      {icon: require("./images/ldotp.svg"), tex: "\\ldotp"},
      {icon: require("./images/cdotp.svg"), tex: "\\cdotp"},
      {icon: require("./images/colon.svg"), tex: "\\colon"},
      {icon: require("./images/dblcolon.svg"), tex: "\\dblcolon"},
      {icon: require("./images/vcentcolon.svg"), tex: "\\vcentcolon"},
      {icon: require("./images/colonapprox.svg"), tex: "\\colonapprox"},
      {icon: require("./images/colonapprox2.svg"), tex: "\\Colonapprox"},
      {icon: require("./images/coloneq.svg"), tex: "\\coloneq"},
      {icon: require("./images/coloneq2.svg"), tex: "\\Coloneq"},
      {icon: require("./images/coloneqq.svg"), tex: "\\coloneqq"},
      {icon: require("./images/coloneqq2.svg"), tex: "\\Coloneqq"},
      {icon: require("./images/colonsim.svg"), tex: "\\colonsim"},
      {icon: require("./images/colonsim2.svg"), tex: "\\Colonsim"},
      {icon: require("./images/eqcolon.svg"), tex: "\\eqcolon"},
      {icon: require("./images/eqcolon2.svg"), tex: "\\Eqcolon"},
      {icon: require("./images/eqqcolon.svg"), tex: "\\eqqcolon"},
      {icon: require("./images/eqqcolon2.svg"), tex: "\\Eqqcolon"},
      {icon: require("./images/wasypropto.svg"), tex: "\\wasypropto"},
      {icon: require("./images/logof.svg"), tex: "\\logof"},
      {icon: require("./images/join2.svg"), tex: "\\Join"}
    ]
  },
  {
    name: "Negative Relations (extended)",
    icon: require("./images/nless.svg"),
    children: [
      {icon: require("./images/nless.svg"), tex: "\\nless"},
      {icon: require("./images/ngtr.svg"), tex: "\\ngtr"},
      {icon: require("./images/nleq.svg"), tex: "\\nleq"},
      {icon: require("./images/ngeq.svg"), tex: "\\ngeq"},
      {icon: require("./images/nleqslant.svg"), tex: "\\nleqslant"},
      {icon: require("./images/ngeqslant.svg"), tex: "\\ngeqslant"},
      {icon: require("./images/nleqq.svg"), tex: "\\nleqq"},
      {icon: require("./images/ngeqq.svg"), tex: "\\ngeqq"},
      {icon: require("./images/lneq.svg"), tex: "\\lneq"},
      {icon: require("./images/gneq.svg"), tex: "\\gneq"},
      {icon: require("./images/lneqq.svg"), tex: "\\lneqq"},
      {icon: require("./images/gneqq.svg"), tex: "\\gneqq"},
      {icon: require("./images/lvertneqq.svg"), tex: "\\lvertneqq"},
      {icon: require("./images/gvertneqq.svg"), tex: "\\gvertneqq"},
      {icon: require("./images/lnsim.svg"), tex: "\\lnsim"},
      {icon: require("./images/gnsim.svg"), tex: "\\gnsim"},
      {icon: require("./images/lnapprox.svg"), tex: "\\lnapprox"},
      {icon: require("./images/gnapprox.svg"), tex: "\\gnapprox"},
      {icon: require("./images/nprec.svg"), tex: "\\nprec"},
      {icon: require("./images/nsucc.svg"), tex: "\\nsucc"},
      {icon: require("./images/npreceq.svg"), tex: "\\npreceq"},
      {icon: require("./images/nsucceq.svg"), tex: "\\nsucceq"},
      {icon: require("./images/precneqq.svg"), tex: "\\precneqq"},
      {icon: require("./images/succneqq.svg"), tex: "\\succneqq"},
      {icon: require("./images/precnsim.svg"), tex: "\\precnsim"},
      {icon: require("./images/succnsim.svg"), tex: "\\succnsim"},
      {icon: require("./images/precnapprox.svg"), tex: "\\precnapprox"},
      {icon: require("./images/succnapprox.svg"), tex: "\\succnapprox"},
      {icon: require("./images/subsetneq.svg"), tex: "\\subsetneq"},
      {icon: require("./images/supsetneq.svg"), tex: "\\supsetneq"},
      {icon: require("./images/subsetneqq.svg"), tex: "\\subsetneqq"},
      {icon: require("./images/supsetneqq.svg"), tex: "\\supsetneqq"},
      {icon: require("./images/nsubseteq.svg"), tex: "\\nsubseteq"},
      {icon: require("./images/nsubseteqq.svg"), tex: "\\nsubseteqq"},
      {icon: require("./images/nsupseteq.svg"), tex: "\\nsupseteq"},
      {icon: require("./images/nsupseteqq.svg"), tex: "\\nsupseteqq"},
      {icon: require("./images/nvdash.svg"), tex: "\\nvdash"},
      {icon: require("./images/nvdash2.svg"), tex: "\\nvDash"},
      {icon: require("./images/nvdash3.svg"), tex: "\\nVDash"},
      {icon: require("./images/nvdash4.svg"), tex: "\\nVdash"},
      {icon: require("./images/varsubsetneq.svg"), tex: "\\varsubsetneq"},
      {icon: require("./images/varsupsetneq.svg"), tex: "\\varsupsetneq"},
      {icon: require("./images/varsubsetneqq.svg"), tex: "\\varsubsetneqq"},
      {icon: require("./images/varsupsetneqq.svg"), tex: "\\varsupsetneqq"},
      {icon: require("./images/ntriangleleft.svg"), tex: "\\ntriangleleft"},
      {icon: require("./images/ntriangleright.svg"), tex: "\\ntriangleright"},
      {icon: require("./images/ntrianglelefteq.svg"), tex: "\\ntrianglelefteq"},
      {icon: require("./images/ntrianglerighteq.svg"), tex: "\\ntrianglerighteq"},
      {icon: require("./images/ncong.svg"), tex: "\\ncong"},
      {icon: require("./images/nsim.svg"), tex: "\\nsim"},
      {icon: require("./images/nmid.svg"), tex: "\\nmid"},
      {icon: require("./images/nshortmid.svg"), tex: "\\nshortmid"},
      {icon: require("./images/nparallel.svg"), tex: "\\nparallel"},
      {icon: require("./images/nshortparallel.svg"), tex: "\\nshortparallel"},
      {icon: require("./images/ntrianglelefteqslant.svg"), tex: "\\ntrianglelefteqslant"},
      {icon: require("./images/ntrianglerighteqslant.svg"), tex: "\\ntrianglerighteqslant"}
    ]
  },
  {
    name: "Dots",
    icon: require("./images/dots.svg"),
    children: [
      {name: require("./images/ldots.svg"), tex: "\\ldots", icon: require("./images/ldots.svg")},
      {name: require("./images/cdots.svg"), tex: "\\cdots", icon: require("./images/cdots.svg")},
      {name: require("./images/vdots.svg"), tex: "\\vdots", icon: require("./images/vdots.svg")},
      {name: require("./images/ddots.svg"), tex: "\\ddots", icon: require("./images/ddots.svg")},
      {name: require("./images/iddots.svg"), tex: "\\iddots", icon: require("./images/iddots.svg")}
    ]
  },
  {
    name: "Delimiters (fixed size)",
    icon: require("./images/brokenvert.svg"),
    children: [
      {icon: require("./images/brokenvert.svg"), tex: "\\brokenvert"},
      {icon: require("./images/lfloor.svg"), tex: "\\lfloor"},
      {icon: require("./images/rfloor.svg"), tex: "\\rfloor"},
      {icon: require("./images/lceil.svg"), tex: "\\lceil"},
      {icon: require("./images/rceil.svg"), tex: "\\rceil"},
      {icon: require("./images/llbracket.svg"), tex: "\\llbracket"},
      {icon: require("./images/rrbracket.svg"), tex: "\\rrbracket"},
      {icon: require("./images/llfloor.svg"), tex: "\\llfloor"},
      {icon: require("./images/rrfloor.svg"), tex: "\\rrfloor"},
      {icon: require("./images/llceil.svg"), tex: "\\llceil"},
      {icon: require("./images/rrceil.svg"), tex: "\\rrceil"},
      {icon: require("./images/lbag2.svg"), tex: "\\Lbag"},
      {icon: require("./images/rbag2.svg"), tex: "\\Rbag"},
      {icon: require("./images/llparenthesis.svg"), tex: "\\llparenthesis"},
      {icon: require("./images/rrparenthesis.svg"), tex: "\\rrparenthesis"},
      {icon: require("./images/binampersand.svg"), tex: "\\binampersand"},
      {icon: require("./images/bindnasrepma.svg"), tex: "\\bindnasrepma"}
    ]
  },
  {
    name: "Miscellaneous (extended)",
    icon: require("./images/fint.svg"), // TODO
    children: [
      {icon: require("./images/digamma.svg"), tex: "\\digamma"},
      {icon: require("./images/varkappa.svg"), tex: "\\varkappa"},
      {icon: require("./images/beth.svg"), tex: "\\beth"},
      {icon: require("./images/daleth.svg"), tex: "\\daleth"},
      {icon: require("./images/gimel.svg"), tex: "\\gimel"},
      {icon: require("./images/ulcorner.svg"), tex: "\\ulcorner"},
      {icon: require("./images/urcorner.svg"), tex: "\\urcorner"},
      {icon: require("./images/llcorner.svg"), tex: "\\llcorner"},
      {icon: require("./images/lrcorner.svg"), tex: "\\lrcorner"},
      {icon: require("./images/hbar.svg"), tex: "\\hbar"},
      {icon: require("./images/hslash.svg"), tex: "\\hslash"},
      {icon: require("./images/vartriangle.svg"), tex: "\\vartriangle"},
      {icon: require("./images/triangledown.svg"), tex: "\\triangledown"},
      {icon: require("./images/square.svg"), tex: "\\square"},
      // {icon: "square2", tex: "\\Square"},
      // {icon: "checkedbox2", tex: "\\CheckedBox"},
      {icon: require("./images/xbox3.svg"), tex: "\\XBox"},
      {icon: require("./images/lozenge.svg"), tex: "\\lozenge"},
      // {icon: "wasylozenge", tex: "\\wasylozenge"},
      {icon: require("./images/circledR.svg"), tex: "\\circledR"},
      {icon: require("./images/circledS.svg"), tex: "\\circledS"},
      {icon: require("./images/measuredangle.svg"), tex: "\\measuredangle"},
      // {icon: "varangle", tex: "\\varangle"},
      {icon: require("./images/nexists.svg"), tex: "\\nexists"},
      {icon: require("./images/mho.svg"), tex: "\\mho"},
      {icon: require("./images/Finv.svg"), tex: "\\Finv"},
      {icon: require("./images/Game.svg"), tex: "\\Game"},
      {icon: require("./images/Bbbk.svg"), tex: "\\Bbbk"},
      {icon: require("./images/backprime.svg"), tex: "\\backprime"},
      {icon: require("./images/varnothing.svg"), tex: "\\varnothing"},
      {icon: require("./images/blacktriangle.svg"), tex: "\\blacktriangle"},
      {icon: require("./images/blacktriangledown.svg"), tex: "\\blacktriangledown"},
      {icon: require("./images/blacksquare.svg"), tex: "\\blacksquare"},
      {icon: require("./images/blacklozenge.svg"), tex: "\\blacklozenge"},
      {icon: require("./images/bigstar.svg"), tex: "\\bigstar"},
      {icon: require("./images/sphericalangle.svg"), tex: "\\sphericalangle"},
      {icon: require("./images/complement.svg"), tex: "\\complement"},
      {icon: require("./images/eth.svg"), tex: "\\eth"},
      {icon: require("./images/diagup.svg"), tex: "\\diagup"},
      {icon: require("./images/diagdown.svg"), tex: "\\diagdown"},
      // {icon: "lightning", tex: "\\lightning"},
      // {icon: "varcopyright", tex: "\\varcopyright"},
      // {icon: "bowtie2", tex: "\\Bowtie"},
      // {icon: "diameter", tex: "\\diameter"},
      // {icon: "invdiameter", tex: "\\invdiameter"},
      // {icon: "bell", tex: "\\bell"},
      // {icon: "hexagon", tex: "\\hexagon"},
      // {icon: "varhexagon", tex: "\\varhexagon"},
      // {icon: "pentagon", tex: "\\pentagon"},
      // {icon: "octagon", tex: "\\octagon"},
      // {icon: "smiley", tex: "\\smiley"},
      // {icon: "blacksmiley", tex: "\\blacksmiley"},
      // {icon: "frownie", tex: "\\frownie"},
      // {icon: "sun", tex: "\\sun"},
      {icon: require("./images/leadsto.svg"), tex: "\\leadsto"},
      // {icon: "circle2", tex: "\\Circle"},
      // {icon: "leftcircle2", tex: "\\Leftcircle"},
      // {icon: "rightcircle2", tex: "\\Rightcircle"},
      // {icon: "circle3", tex: "\\CIRCLE"},
      // {icon: "leftcircle3", tex: "\\LEFTCIRCLE"},
      // {icon: "rightcircle3", tex: "\\RIGHTCIRCLE"},
      // {icon: "leftcircle4", tex: "\\LEFTcircle"},
      // {icon: "rightcircle4", tex: "\\RIGHTcircle"},
      // {icon: "leftturn", tex: "\\leftturn"},
      // {icon: "rightturn", tex: "\\rightturn"},
      // {icon: "AC", tex: "\\AC"},
      // {icon: "HF", tex: "\\HF"},
      // {icon: "VHF", tex: "\\VHF"},
      // {icon: "photon", tex: "\\photon"},
      // {icon: "gluon", tex: "\\gluon"},
      // {icon: "permil", tex: "\\permil"},
      // {icon: "cent", tex: "\\cent"},
      {icon: require("./images/yen.svg"), tex: "\\yen"},
      // {icon: "hexstar", tex: "\\hexstar"},
      // {icon: "varhexstar", tex: "\\varhexstar"},
      // {icon: "davidsstar", tex: "\\davidsstar"},
      {icon: require("./images/maltese.svg"), tex: "\\maltese"},
      // {icon: "kreuz", tex: "\\kreuz"},
      // {icon: "ataribox", tex: "\\ataribox"},
      // {icon: "xbox3", tex: "\\XBox"},
      // {icon: "checked", tex: "\\checked"},
      {icon: require("./images/checkmark.svg"), tex: "\\checkmark"},
      // {icon: "eighthnote", tex: "\\eighthnote"},
      // {icon: "quarternote", tex: "\\quarternote"},
      // {icon: "halfnote", tex: "\\halfnote"},
      // {icon: "fullnote", tex: "\\fullnote"},
      // {icon: "twonotes", tex: "\\twonotes"},
      // {icon: "female", tex: "\\female"},
      // {icon: "male", tex: "\\male"},
      // {icon: "vernal", tex: "\\vernal"},
      // {icon: "ascnode", tex: "\\ascnode"},
      // {icon: "descnode", tex: "\\descnode"},
      // {icon: "fullmoon", tex: "\\fullmoon"},
      // {icon: "newmoon", tex: "\\newmoon"},
      // {icon: "leftmoon", tex: "\\leftmoon"},
      // {icon: "rightmoon", tex: "\\rightmoon"},
      // {icon: "astrosun", tex: "\\astrosun"},
      // {icon: "mercury", tex: "\\mercury"},
      // {icon: "venus", tex: "\\venus"},
      // {icon: "earth", tex: "\\earth"},
      // {icon: "mars", tex: "\\mars"},
      // {icon: "jupiter", tex: "\\jupiter"},
      // {icon: "saturn", tex: "\\saturn"},
      // {icon: "uranus", tex: "\\uranus"},
      // {icon: "neptune", tex: "\\neptune"},
      // {icon: "pluto", tex: "\\pluto"},
      // {icon: "aries", tex: "\\aries"},
      // {icon: "taurus", tex: "\\taurus"},
      // {icon: "gemini", tex: "\\gemini"},
      // {icon: "cancer", tex: "\\cancer"},
      // {icon: "leo", tex: "\\leo"},
      // {icon: "virgo", tex: "\\virgo"},
      // {icon: "libra", tex: "\\libra"},
      // {icon: "scorpio", tex: "\\scorpio"},
      // {icon: "sagittarius", tex: "\\sagittarius"},
      // {icon: "capricornus", tex: "\\capricornus"},
      // {icon: "aquarius", tex: "\\aquarius"},
      // {icon: "pisces", tex: "\\pisces"},
      // {icon: "APLbox", tex: "\\APLbox"},
      // {icon: "APLcomment", tex: "\\APLcomment"},
      // {icon: "APLdown", tex: "\\APLdown"},
      // {icon: "APLdownarrowbox", tex: "\\APLdownarrowbox"},
      // {icon: "APLinput", tex: "\\APLinput"},
      // {icon: "APLinv", tex: "\\APLinv"},
      // {icon: "APLleftarrowbox", tex: "\\APLleftarrowbox"},
      // {icon: "APLlog", tex: "\\APLlog"},
      // {icon: "APLrightarrowbox", tex: "\\APLrightarrowbox"},
      // {icon: "APLstar", tex: "\\APLstar"},
      // {icon: "APLup", tex: "\\APLup"},
      // {icon: "APLuparrowbox", tex: "\\APLuparrowbox"}
    ]
  }
];
